### PR TITLE
Change log level from warn to debug

### LINKED ISSUE #1005: Tweak output messages
After some analysis on reports, there might be room to speed linting a bit by tweaking a bit our output. Let's discuss here some ideas:

1. Change the `WARN` when super-linter is not able to determine the type of a file to `DEBUG`. Rationale: we don't really expect the user to do something here, but it's a useful information in debug.
1. Move information about a linter to `DEBUG` when there are no files to lint. Rationale: having a lot a noise about unrelated linters makes it harder checking the results of the ones you're really interested.

### PR DESCRIPTION
**Pull request by GaboFDC**
Fixes #1005 

## Proposed Changes

1. Change 'Failed to get filetype' log lever from warn to debug
1. Move 'Linting x file' to be printed only if files are found

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by ferrarimarco** [comment]
While it's trivial to analyze the first change by checking the log, the second one is harder because I suppose we have all file types to lint, so I had to check if the lines for JSX, TSX, and OpenAPI were correctly absent. Note that these tests are being added in #1032 

So I guess it's a green light!

**Review by ferrarimarco — APPROVED** [review]

**Comment by ferrarimarco** [comment]
(I don't have approval rights tho) /shrug

**Comment by GaboFDC** [comment]
> While it's trivial to analyze the first change by checking the log, the second one is harder because I suppose we have all file types to lint, so I had to check if the lines for JSX, TSX, and OpenAPI were correctly absent (tests that are currently missing). Note that these tests are being added in #1032
> 
> So I guess it's a green light!

Yeah, I also build it locally and pointed to some random files, and it works as expected:

```bash
 ~/GIT/super-linter  $ docker run  -e RUN_LOCAL=true -v /tmp/gabo/:/tmp/lint gabo-super-linter:latest
--------------------------------------------------------------------------------

                              /@@#///////@@/(@//@%/(@.@(       @@
                          @@//////////////////////////////#*  @@@
                        @////@//(///////////@@@@@///@//@/@**//@@(
                      @///////@///////////////@@@@    (           @,
                     @/(&/@////////////////////                     @
                    @////////////////////////@@                      @
                  @%////////(//////////%/////&@            @@       *,@           ______________
             @@@@@/@/#/////(&//////////////////                       .@         /              \
        *@@@@@.    .%///(//@//////////////////&.   .@@,                 @%      / Don't mind me  \
      @@%           .&@&&/@.@//&/////(//////////    @@@@@@@@@         .. &@    / I'm just looking \
    @@%               @@@@@   @&/////////////////#   @/       V  @@/ ,@@@ @   <  for some trash... |
@@@%                   @@@@        .%@@@@//////#@ @   @@         @     .,.     \__________________/
                                          @@@/@(  (@@@@% @/\      %
                                           @@@@(    .     .@@/\   #
                                             @                  %@%

--------------------------------------------------------------------------------
2020-11-25 17:00:11 [INFO]   ---------------------------------------------
2020-11-25 17:00:11 [INFO]   --- GitHub Actions Multi Language Linter ----
2020-11-25 17:00:11 [INFO]    - Image Creation Date:[]
2020-11-25 17:00:11 [INFO]    - Image Revision:[]
2020-11-25 17:00:11 [INFO]    - Image Version:[]
2020-11-25 17:00:11 [INFO]   ---------------------------------------------
2020-11-25 17:00:11 [INFO]   ---------------------------------------------
2020-11-25 17:00:11 [INFO]   The Super-Linter source code can be found at:
2020-11-25 17:00:11 [INFO]    - https://github.com/github/super-linter
2020-11-25 17:00:11 [INFO]   ---------------------------------------------
2020-11-25 17:00:11 [INFO]   --------------------------------------------
2020-11-25 17:00:11 [INFO]   Gathering GitHub information...
2020-11-25 17:00:11 [INFO]   NOTE: ENV VAR [RUN_LOCAL] has been set to:[true]
2020-11-25 17:00:11 [INFO]   bypassing GitHub Actions variables...
2020-11-25 17:00:11 [INFO]   Linting all files in mapped directory:[/tmp/lint]
2020-11-25 17:00:11 [INFO]   Successfully found:[GITHUB_TOKEN]
2020-11-25 17:00:11 [INFO]   --------------------------------------------
2020-11-25 17:00:11 [INFO]   Gathering user validation information...
2020-11-25 17:00:15 [INFO]   ---------------------------------
2020-11-25 17:00:15 [INFO]   ------ File list to check: ------
2020-11-25 17:00:15 [INFO]   ---------------------------------
2020-11-25 17:00:16 [INFO]   ----------------------------------------------
2020-11-25 17:00:16 [INFO]   Successfully gathered list of files...
2020-11-25 17:00:16 [WARN]   No Ansible base directory found at:[/tmp/lint/ansible]
2020-11-25 17:00:16 [INFO]
2020-11-25 17:00:16 [INFO]   ----------------------------------------------
2020-11-25 17:00:16 [INFO]   ----------------------------------------------
2020-11-25 17:00:16 [INFO]   Linting [BASH] files...
2020-11-25 17:00:16 [INFO]   ----------------------------------------------
2020-11-25 17:00:16 [INFO]   ----------------------------------------------
2020-11-25 17:00:16 [INFO]   ---------------------------
2020-11-25 17:00:16 [INFO]   File:[/tmp/lint/shell_bad_1.sh]
2020-11-25 17:00:17 [INFO]    - File:[shell_bad_1.sh] failed test case (Error code: 1) with [shellcheck] successfully
2020-11-25 17:00:17 [INFO]
2020-11-25 17:00:17 [INFO]   ----------------------------------------------
2020-11-25 17:00:17 [INFO]   ----------------------------------------------
2020-11-25 17:00:17 [INFO]   Linting [BASH_EXEC] files...
2020-11-25 17:00:17 [INFO]   ----------------------------------------------
2020-11-25 17:00:17 [INFO]   ----------------------------------------------
2020-11-25 17:00:17 [INFO]   ---------------------------
2020-11-25 17:00:17 [INFO]   File:[/tmp/lint/shell_bad_1.sh]
2020-11-25 17:00:17 [INFO]    - File:[shell_bad_1.sh] failed test case (Error code: 1) with [bash-exec] successfully
2020-11-25 17:00:17 [INFO]
2020-11-25 17:00:17 [INFO]   ----------------------------------------------
2020-11-25 17:00:17 [INFO]   ----------------------------------------------
2020-11-25 17:00:17 [INFO]   Linting [COFFEESCRIPT] files...
2020-11-25 17:00:17 [INFO]   ----------------------------------------------
2020-11-25 17:00:17 [INFO]   ----------------------------------------------
2020-11-25 17:00:17 [INFO]   ---------------------------
2020-11-25 17:00:17 [INFO]   File:[/tmp/lint/coffeescript_bad_1.coffee]
2020-11-25 17:00:17 [INFO]    - File:[coffeescript_bad_1.coffee] failed test case (Error code: 1) with [coffeelint] successfully
2020-11-25 17:00:17 [INFO]
2020-11-25 17:00:17 [INFO]   ----------------------------------------------
2020-11-25 17:00:17 [INFO]   ----------------------------------------------
2020-11-25 17:00:17 [INFO]   Linting [ENV] files...
2020-11-25 17:00:17 [INFO]   ----------------------------------------------
2020-11-25 17:00:17 [INFO]   ----------------------------------------------
2020-11-25 17:00:17 [INFO]   ---------------------------
2020-11-25 17:00:17 [INFO]   File:[/tmp/lint/.env]
2020-11-25 17:00:17 [ERROR]   Found errors in [dotenv-linter] linter!
2020-11-25 17:00:17 [ERROR]   Error code: 1. Command output:[.env:4 UnorderedKey: The POSTGRESQL_PASSWORD key should go before the POSTGRESQL_USER key
.env:5 UnorderedKey: The POSTGRESQL_DATABASE key should go before the POSTGRESQL_PASSWORD key
.env:6 UnorderedKey: The POSTGRESQL_HOST key should go before the POSTGRESQL_PASSWORD key
.env:8 UnorderedKey: The POSTGRESQL_PORT key should go before the POSTGRESQL_USER key
.env:9 UnorderedKey: The POSTGRESQL_POOL key should go before the POSTGRESQL_PORT key
.env:21 UnorderedKey: The SNEAKERS_PREFETCH key should go before the SNEAKERS_SHARE_THREADS key
.env:22 UnorderedKey: The SNEAKERS_HEARTBEAT key should go before the SNEAKERS_PREFETCH key

Found 7 problems]
2020-11-25 17:00:18 [INFO]
2020-11-25 17:00:18 [INFO]   ----------------------------------------------
2020-11-25 17:00:18 [INFO]   ----------------------------------------------
2020-11-25 17:00:18 [INFO]   Linting [JAVASCRIPT_ES] files...
2020-11-25 17:00:18 [INFO]   ----------------------------------------------
2020-11-25 17:00:18 [INFO]   ----------------------------------------------
2020-11-25 17:00:18 [INFO]   ---------------------------
2020-11-25 17:00:18 [INFO]   File:[/tmp/lint/asd.js]
2020-11-25 17:00:19 [INFO]    - File:[asd.js] was linted with [eslint] successfully
2020-11-25 17:00:19 [INFO]   ---------------------------
2020-11-25 17:00:19 [INFO]   File:[/tmp/lint/javascript_bad_1.js]
2020-11-25 17:00:21 [INFO]    - File:[javascript_bad_1.js] failed test case (Error code: 1) with [eslint] successfully
2020-11-25 17:00:21 [INFO]
2020-11-25 17:00:21 [INFO]   ----------------------------------------------
2020-11-25 17:00:21 [INFO]   ----------------------------------------------
2020-11-25 17:00:21 [INFO]   Linting [JAVASCRIPT_STANDARD] files...
2020-11-25 17:00:21 [INFO]   ----------------------------------------------
2020-11-25 17:00:21 [INFO]   ----------------------------------------------
2020-11-25 17:00:21 [INFO]   ---------------------------
2020-11-25 17:00:21 [INFO]   File:[/tmp/lint/asd.js]
2020-11-25 17:00:22 [INFO]    - File:[asd.js] was linted with [standard] successfully
2020-11-25 17:00:22 [INFO]   ---------------------------
2020-11-25 17:00:22 [INFO]   File:[/tmp/lint/javascript_bad_1.js]
2020-11-25 17:00:23 [INFO]    - File:[javascript_bad_1.js] failed test case (Error code: 1) with [standard] successfully
2020-11-25 17:00:23 [INFO]
2020-11-25 17:00:23 [INFO]   ----------------------------------------------
2020-11-25 17:00:23 [INFO]   ----------------------------------------------
2020-11-25 17:00:23 [INFO]   Linting [JSON] files...
2020-11-25 17:00:23 [INFO]   ----------------------------------------------
2020-11-25 17:00:23 [INFO]   ----------------------------------------------
2020-11-25 17:00:23 [INFO]   ---------------------------
2020-11-25 17:00:23 [INFO]   File:[/tmp/lint/policy_v1.json]
2020-11-25 17:00:24 [INFO]    - File:[policy_v1.json] was linted with [jsonlint] successfully
2020-11-25 17:00:24 [INFO]
2020-11-25 17:00:24 [INFO]   ----------------------------------------------
2020-11-25 17:00:24 [INFO]   ----------------------------------------------
2020-11-25 17:00:24 [INFO]   Linting [POWERSHELL] files...
2020-11-25 17:00:24 [INFO]   ----------------------------------------------
2020-11-25 17:00:24 [INFO]   ----------------------------------------------
2020-11-25 17:00:24 [INFO]   ---------------------------
2020-11-25 17:00:24 [INFO]   File:[/tmp/lint/powershell_bad_1.ps1]
2020-11-25 17:00:25 [INFO]    - File:[powershell_bad_1.ps1] failed test case (Error code: 5) with [pwsh] successfully
2020-11-25 17:00:26 [INFO]
2020-11-25 17:00:26 [INFO]   ----------------------------------------------
2020-11-25 17:00:26 [INFO]   ----------------------------------------------
2020-11-25 17:00:26 [INFO]   Linting [YAML] files...
2020-11-25 17:00:26 [INFO]   ----------------------------------------------
2020-11-25 17:00:26 [INFO]   ----------------------------------------------
2020-11-25 17:00:26 [INFO]   ---------------------------
2020-11-25 17:00:26 [INFO]   File:[/tmp/lint/fixtures/addresses.yml]
2020-11-25 17:00:26 [INFO]    - File:[addresses.yml] was linted with [yamllint] successfully
2020-11-25 17:00:26 [INFO]   ---------------------------
2020-11-25 17:00:26 [INFO]   File:[/tmp/lint/fixtures/documents.yml]
2020-11-25 17:00:26 [INFO]    - File:[documents.yml] was linted with [yamllint] successfully
2020-11-25 17:00:26 [INFO]   ---------------------------
2020-11-25 17:00:26 [INFO]   File:[/tmp/lint/fixtures/policies.yml]
2020-11-25 17:00:26 [INFO]    - File:[policies.yml] was linted with [yamllint] successfully
2020-11-25 17:00:26 [INFO]   ---------------------------
2020-11-25 17:00:26 [INFO]   File:[/tmp/lint/fixtures/policy_holders.yml]
2020-11-25 17:00:26 [INFO]    - File:[policy_holders.yml] was linted with [yamllint] successfully
2020-11-25 17:00:26 [INFO]   ---------------------------
2020-11-25 17:00:26 [INFO]   File:[/tmp/lint/fixtures/policy_number_sequences.yml]
2020-11-25 17:00:26 [INFO]    - File:[policy_number_sequences.yml] was linted with [yamllint] successfully
2020-11-25 17:00:26 [INFO]   ---------------------------
2020-11-25 17:00:26 [INFO]   File:[/tmp/lint/fixtures/policy_settings.yml]
2020-11-25 17:00:26 [INFO]    - File:[policy_settings.yml] was linted with [yamllint] successfully
2020-11-25 17:00:26 [INFO]   ---------------------------
2020-11-25 17:00:26 [INFO]   File:[/tmp/lint/fixtures/policy_versions.yml]
2020-11-25 17:00:26 [INFO]    - File:[policy_versions.yml] was linted with [yamllint] successfully
2020-11-25 17:00:26 [INFO]   ----------------------------------------------
2020-11-25 17:00:26 [INFO]   ----------------------------------------------
2020-11-25 17:00:26 [INFO]   Generated reports:
2020-11-25 17:00:26 [INFO]   ----------------------------------------------
2020-11-25 17:00:26 [INFO]   ----------------------------------------------
2020-11-25 17:00:26 [INFO]   Reports generated in folder /tmp/lint/super-linter.report
2020-11-25 17:00:26 [WARN]   Report output folder (/tmp/lint/super-linter.report) does NOT exist.
2020-11-25 17:00:26 [INFO]   ----------------------------------------------
2020-11-25 17:00:26 [INFO]   ----------------------------------------------
2020-11-25 17:00:26 [INFO]   The script has completed
2020-11-25 17:00:26 [INFO]   ----------------------------------------------
2020-11-25 17:00:26 [INFO]   ----------------------------------------------
2020-11-25 17:00:26 [ERROR]   ERRORS FOUND in ENV:[1]
2020-11-25 17:00:26 [FATAL]   Exiting with errors found!
```

**Review by admiralAwkbar — APPROVED** [review]
dope

**Pull request merged**
