### PR TITLE
Adding C# lint

### PR DESCRIPTION
**Pull request by eddynaka**
Fixes #

## Proposed Changes

1. ...
2. ...
3. ...

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer 
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by eddynaka** [comment]
I have some questions:
1. how to test
2. how should i install the tool? Right now, to install i have to use the following command: `dotnet tool install -g dotnet-format` and i have to have dotnet installed

**Comment by admiralAwkbar** [comment]
@eddynaka Thanks for the help!

For your questions:
- You can test by creating the docker file locally and then telling it to run against your tests locally
- Installing to Alpine was a little bit of fun but I think i got that resolved... Was not as straight forward as hoped

**Comment by eddynaka** [comment]
> @eddynaka Thanks for the help!
> 
> For your questions:
> 
> * You can test by creating the docker file locally and then telling it to run against your tests locally
> * Installing to Alpine was a little bit of fun but I think i got that resolved... Was not as straight forward as hoped

Thanks for the help. I was looking at ur changes!

Do u think that is viable and that would work?

**Comment by IAmHughes** [comment]
@admiralAwkbar I updated the `bad` test. Basically it should fail due to the opening curly braces not being on newlines (a .NET standard). Good test looked good to me to start with. 👍

**Comment by admiralAwkbar** [comment]
@eddynaka 
Can you finish with the writing of the good and bad files and the solution file?

looks like it says:
```bash
  File:[/tmp/lint/.automation/test/csharp/csharp_good_01.cs]
2020-08-25 19:30:43 [ERROR ]   Found errors in [dotnet-format] linter!
2020-08-25 19:30:43 [ERROR ]   [  Could not find a MSBuild project file or solution file in '/tmp/lint/.automation/test'. Specify which to use with the --workspace option.]
2020-08-25 19:30:43 [ERROR ]   Linter CMD:[dotnet-format --check --include /tmp/lint/.automation/test/csharp/csharp_good_01.cs]`
```

**Comment by eddynaka** [comment]
> @eddynaka
> Can you finish with the writing of the good and bad files and the solution file?
> 
> looks like it says:
> 
> ```shell
>   File:[/tmp/lint/.automation/test/csharp/csharp_good_01.cs]
> 2020-08-25 19:30:43 [ERROR ]   Found errors in [dotnet-format] linter!
> 2020-08-25 19:30:43 [ERROR ]   [  Could not find a MSBuild project file or solution file in '/tmp/lint/.automation/test'. Specify which to use with the --workspace option.]
> 2020-08-25 19:30:43 [ERROR ]   Linter CMD:[dotnet-format --check --include /tmp/lint/.automation/test/csharp/csharp_good_01.cs]`
> ```

I will check the command line. Since we don't have a sln/csproj, dotnet-format is complaining. let me try some stuff.

**Comment by admiralAwkbar** [comment]
@IAmHughes If you see the error about the `sln` file, can you handle that as well?

**Comment by IAmHughes** [comment]
> @IAmHughes If you see the error about the sln file, can you handle that as well?

@admiralAwkbar looks like my build failed due to something unrelated (`.phar` file issue). Re-running now 👍

**Comment by eddynaka** [comment]
Testing locally, it looks like we pass an array of files to dotnet-format. I'm opening an issue to that. Besides that, I think we will have to change to something like this: `dotnet-format --check --folder .\`

**Comment by IAmHughes** [comment]
@admiralAwkbar @eddynaka I agree with ☝️ https://github.com/github/super-linter/pull/615#issuecomment-680232782

Test failed for that reason it seems: https://github.com/github/super-linter/runs/1028277188#step:4:190

**Comment by eddynaka** [comment]
> @admiralAwkbar @eddynaka I agree with ☝️ [#615 (comment)](https://github.com/github/super-linter/pull/615#issuecomment-680232782)
> 
> Test failed for that reason it seems: https://github.com/github/super-linter/runs/1028277188#step:4:190

Would be bad to remove the array of files and test the .\ entirely?

**Comment by eddynaka** [comment]
> @admiralAwkbar @eddynaka I agree with ☝️ [#615 (comment)](https://github.com/github/super-linter/pull/615#issuecomment-680232782)
> 
> Test failed for that reason it seems: https://github.com/github/super-linter/runs/1028277188#step:4:190

i was trying to change the command line, but it didn't work in the script. But, if you run locally, it works fine:
`dotnet-format --folder --include filea.cs fileb.cs --check`

What i did: tried to add --check in the end of the comand line but it didn't work. Do i need to add something else? Not familiar with this script language.

**Comment by IAmHughes** [comment]
> What i did: tried to add --check in the end of the comand line but it didn't work. Do i need to add something else? Not familiar with this script language.

@eddynaka thanks for the working command. @admiralAwkbar and I paired this morning and we think we fixed it in: https://github.com/github/super-linter/pull/615/commits/454fa09b81d128512ae2ec894c2c301c4a05a31a

We still have another issue with the `bad` test failing properly locally, but not in the automation, so we'll investigate that further later.

**Comment by eddynaka** [comment]
> > What i did: tried to add --check in the end of the comand line but it didn't work. Do i need to add something else? Not familiar with this script language.
> 
> @eddynaka thanks for the working command. @admiralAwkbar and I paired this morning and we think we fixed it in: [454fa09](https://github.com/github/super-linter/commit/454fa09b81d128512ae2ec894c2c301c4a05a31a)
> 
> We still have another issue with the `bad` test failing properly locally, but not in the automation, so we'll investigate that further later.

```
 C:\super-linter> dotnet-format --folder --check --include .\**\*.cs
  Formatting code files in workspace 'C:\Microsoft\super-linter'.
  super-linter\.automation\test\csharp\csharp_bad_01.cs(3,21): Fix whitespace formatting.
  super-linter\.automation\test\csharp\csharp_bad_01.cs(3,23): Fix whitespace formatting.
  super-linter\.automation\test\csharp\csharp_bad_01.cs(4,16): Fix whitespace formatting.
  super-linter\.automation\test\csharp\csharp_bad_01.cs(4,18): Fix whitespace formatting.
  super-linter\.automation\test\csharp\csharp_bad_01.cs(5,36): Fix whitespace formatting.
  super-linter\.automation\test\csharp\csharp_bad_01.cs(5,38): Fix whitespace formatting.
  super-linter\.automation\test\csharp\csharp_bad_01.cs(6,40): Fix whitespace formatting.
  super-linter\.automation\test\csharp\csharp_bad_01.cs(7,6): Fix whitespace formatting.
  Formatted code file 'C:\super-linter\.automation\test\csharp\csharp_bad_01.cs'.
  Format complete in 983ms.
```

If I pass `--include .\**\*.cs` or `--include .\.automation\test\csharp\csharp_bad_01.cs` it works fine.
If i pass `--include c:\folder\.automation\test\csharp\csharp_bad_01.cs` it does not work.

I pushed a commit trying to use the first option. but that didn't work as well. not sure if i did it wrong.

**Comment by admiralAwkbar** [comment]
@eddynaka @jwiebalk and I found it!
It appears that `dotnet-format` writes back to `tty` and not `stdout` so it was failing to catch the output and error codes...
Super tricky to find, but I think this caught it now...

**Review by IAmHughes — DISMISSED** [review]
Nice work getting it over the line @admiralAwkbar

**Comment by eddynaka** [comment]
thank you @admiralAwkbar @IAmHughes

**Pull request merged**
