### PR TITLE
Use Git to update major version and latest tags

### LINKED ISSUE #3372: The version updater workflow fails with permission issues
## Describe the bug

I think the latest release may have broken something? Our CI runs just started failing with the following error:

```
[Lint Code Base](https://github.com/carmigo/eblock-graphql/actions/runs/3151226047/jobs/5125073568#step:1:24)
Unable to resolve action `github/super-linter@v4`, unable to find version `v4`
```

## Expected behavior

The action should work.

## Steps to Reproduce

Run a workflow that uses this action.

## Additional context

I was able to get unblocked by using the full version number:

`github/super-linter@v4.9.6`

### PR DESCRIPTION
**Pull request by ferrarimarco**
Fixes #3372

## Proposed Changes

1. Use Git to update the `vMAJOR_VERSION` and `latest` Git tags instead of relying on an action.

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [x] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Review by admiralAwkbar — APPROVED** [review]
very fancy

**Comment by ferrarimarco** [comment]
@admiralAwkbar sorry for bothering you again. Mind having another look? I've pushed another commit to streamline things a bit. Thanks!

**Review by admiralAwkbar — APPROVED** [review]
very dank

**Comment by ferrarimarco** [comment]
Thanks!

**Pull request merged**
