### PR TITLE
Certs

### PR DESCRIPTION
**Pull request by admiralAwkbar**
- Adding ability for users to insert their certs to help solve `self hosted runners`
- This also helps users on GHES or GHAE

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@Link-  This should help solve your issue.

I pushed the image to:
```bash
ghcr.io/github/super-linter:cert
```

**Comment by Link-** [comment]
Testing this now

**Comment by admiralAwkbar** [comment]
@Link- thank you for all the hard work on testing this! you the best!

**Comment by Link-** [comment]
@admiralAwkbar tested locally and we're good to 🚀 ✨ ✨ ✨ PR!

```sh
***
]
2021-04-26 13:49:03 [INFO]   Moved cert into location, adding to trust store...
2021-04-26 13:49:03 [INFO]   Successfully added cert to trust store
2021-04-26 13:49:03 [DEBUG]   Building file list...
2021-04-26 13:49:03 [DEBUG]   Validate all code base: true...
```

source

**Review by jwiebalk — APPROVED** [review]

**Pull request merged**
