### PR TITLE
Fix yaml

### PR DESCRIPTION
**Pull request by GaboFDC**
Fixes a rebase that removed this small change.

## Proposed Changes

1. Fix YAML linting

## Readiness Checklist

- [ ] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by zkoppert** [comment]
Looks like this is something that should have been caught by a test. Is it correct that before this fix the `YAML` linting wouldn't even run? Would you mind writing a test to cover this?

**Comment by nemchik** [comment]
I think we also need to rename https://github.com/github/super-linter/tree/gf_fix_yaml/.automation/test/yml (the folder and files) and change https://github.com/github/super-linter/blob/d0c3b77253b69fe4c07435a3ace0d0a5a2c8579d/lib/worker.sh#L607 to
```suggestion
TestCodebase "YAML" "yamllint" "yamllint -c ${YAML_LINTER_RULES}" ".*\.\(yml\|yaml\)\$" "yaml"
```

**Comment by GaboFDC** [comment]
> Looks like this is something that should have been caught by a test. Is it correct that before this fix the `YAML` linting wouldn't even run? Would you mind writing a test to cover this?
It doesn't tun on lint all code base. For this, I opened #475

**Comment by GaboFDC** [comment]
> I think we also need to rename [`gf_fix_yaml`/.automation/test/yml](https://github.com/github/super-linter/tree/gf_fix_yaml/.automation/test/yml?rgh-link-date=2020-07-30T23%3A03%3A38Z) (the folder and files) and change
> 
> https://github.com/github/super-linter/blob/d0c3b77253b69fe4c07435a3ace0d0a5a2c8579d/lib/worker.sh#L607
> to
> 
> ```
> TestCodebase "YAML" "yamllint" "yamllint -c ${YAML_LINTER_RULES}" ".*\.\(yml\|yaml\)\$" "yaml"
> ```

Done, although this was independently, but yeah for consistency it's fine

**Comment by nemchik** [comment]
Agreed, that is just to prevent confusion. This looks good to me.

**Pull request merged**
