### PR TITLE
testing and fixes

### LINKED ISSUE #949: Add more pre-release testing
**Is your feature request related to a problem? Please describe.**
The GitHub super-linter has published a number of bad releases since go-live which have been left in place for hours and days. This is particularly a problem as this project does not follow versioning (see #708 ) so this affects even those repos that do not upgrade, and also affects all forks and branches meaning even if we try to [work around a bad release](https://github.com/github/super-linter/issues/938#issuecomment-720977157) it requires all those forks and branches to pick up the latest workaround. This is a big problem when all linting workflows across many projects suddenly break.

The latest example is #938. While that issue can be dedicated to fixing that immediate problem I would like to raise this separate issue to track how this was able to get through to a release. Consider this almost the RCA and follow up actions to try to prevent #938 happening again.

**Describe the solution you'd like**
Add test cases to prevent the cause of issues like #938.

**Describe alternatives you've considered**
The super-linter should also:
- Fix versioning - #708 
- Add post release checks to immediately identify issues on a bad release - #948

**Additional context**
Issues that have broken the linter (not an exhaustive list):
- #704
- #938

### PR DESCRIPTION
**Pull request by admiralAwkbar**
This closes #949 

- Adding more testing
- Set exec bit to true vs false
- Fix tap reporting

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@ferrarimarco I dont understand tap all that well and would love some help getting those up to date again... its crazy///

**Comment by ferrarimarco** [comment]
#983 :) We're working on the same stuff

**Comment by ferrarimarco** [comment]
With the exec bit I went a different route to avoid breaking existing users. I enabled that behavior in our build configs

**Comment by admiralAwkbar** [comment]
@ferrarimarco lol nice! ill throw this pr away! i have another fix i want to do :)

**Comment by ferrarimarco** [comment]
Feel free to commit there! :)

**Pull request closed without merging**
