### PR TITLE
Creating more functions

### PR DESCRIPTION
**Pull request by admiralAwkbar**
This PR will cover:
- Breaking the monolith `linter.sh` into a main, and sub-functions files

This should help with maintaining the structure and allow for easier growth

### CODE REVIEW

**Comment by zkoppert** [comment]
Do we need to edit the wiki page on how to add a new language support to reference which of these new files to edit?

**Comment by zkoppert** [comment]
Love that this has its own readme. The main one is getting large.

**Comment by admiralAwkbar** [comment]
@zkoppert all functions are still labeled the same, but I think we should update the doc to show the new file locations as well :)

**Comment by admiralAwkbar** [comment]
@zkoppert Updated wiki

**Comment by admiralAwkbar** [comment]
@zkoppert yes I think this will be v3...

**Pull request merged**
