### PR TITLE
Dynamically invoke tests

### PR DESCRIPTION
**Pull request by ferrarimarco**
# Proposed Changes

1. Merge `LintCodeBase` with `TestCodeBase`. Those functions shared 80% of code, no need to have two. By passing `TEST_CASE_RUN` as a parameter to `LintCodeBase`, we can specialize the behavior when we need to test.
1. Reuse the logic in `buildFileList.sh` to build the lists of files to lint for tests as well. Test files are not included in non-test runs (i.e. when `TEST_CASE_RUN` is not `true`).
1. If `TEST_CASE_RUN` is `false`, the behavior is the same as it was before. If `TEST_CASE_RUN` is `true`, the following happens:
    1. Adjust the INFO output header.
    1. Change the workspace path from `${GITHUB_WORKSPACE}` to `${GITHUB_WORKSPACE}/${TEST_CASE_FOLDER}`
    1. Set the `FILE_STATUS` accordingly, and not blindly to `good` as it is for non-test runs.
    1. Enable checking the results of the linting as `TestCodeBase` did.
    1. Compare TAP reports with expectations when available.
    1. Check if there is at least one test for each language.
1. Remove the `RunTestCases` function because we dynamically invoke linters in `LintCodeBase` now.
1. Rename test directories to match the language name, so we can deduce the test directory from such name. The affected test directories are:
    1. `shell` -> `bash`, `bash_exec`
    1. `docker` -> `dockerfile`, `dockerfile_hadolint`
    1. `golang` -> `go`
    1. `javascript` -> `javascript_es`, `javascript_standard`
    1. `kubernetes` -> `kubernetes_kubeval`
    1. `php` -> `php_builtin`, `php_phpcs`, `php_psalm`
    1. `python` -> `python_black`, `python_flake8`, `python_pylint`
    1. `snakemake` -> `snakemake_lint`, `snakemake_snakefmt`
    1. `typescript` -> `typescript_es`, `typescript_standard`
1. Move all the corner cases to exclude files from the file list to `buildFileList.sh`. We now exclude:
    1. `node_modules` directory
    1. `.git` directory
    1. Python virtual environment directory
    1. Ruby environment directory
    1. Invalid shell scripts
1. Renamed the linter for `R`, from `lintr` to `R`, so that we don't have to account for this special case when checking if the command is available.
1. Don't use a `PRINT_ARRAY` in `LintCodeBase`, because it makes debugging harder, changing the order of output messages.
1. Add debug statements to print the list of files before and after applying the regexes to include or exclude files.
1. In preparation of merging `LintAnsibleFiles` with `LintCodeBase`, following suit :), I moved the validation of the `ansible-lint` command where we validate other linters.
1. Add a debug statement to print the stdout of the linter. Thanks to this, I was able to solve the issue with Javascript and Typescript tests (see below).
1. Fix `TYPESCRIPT_ES` and `JAVASCRIPT_ES` tests that were silently dropped because eslint ignores paths with dotfiles and dotfolders by default. For this, I added a `.eslintignore` file that allowed scanning the `.automation` directory.

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by ferrarimarco** [comment]
@admiralAwkbar @GaboFDC @nemchik there's a build failure I don't understand. Can you help me here? Thanks!

**Comment by ferrarimarco** [comment]
Here's some eslint debug output:

```shell
2020-10-17 13:12:58 [INFO  ]   ----------------------------------------------                                                                                                                                                                                                                                                2020-10-17 13:12:58 [INFO  ]   ----------------------------------------------                                                                                                                                                                                                                                                2020-10-17 13:12:58 [INFO  ]   Testing Codebase [TYPESCRIPT_ES] files...                                                                                                                                                                                                                                                     2020-10-17 13:12:58 [INFO  ]   ----------------------------------------------                                                                                                                                                                                                                                                2020-10-17 13:12:58 [INFO  ]   ----------------------------------------------                                                                                                                                                                                                                                                2020-10-17 13:12:58 [DEBUG ]   SKIP_FLAG: 0, list of files to lint: /tmp/lint/.automation/test/typescript_es/typescript_bad_1.ts /tmp/lint/.automation/test/typescript_es/typescript_good_1.ts /tmp/lint/.automation/test/typescript_standard/typescript_bad_1.ts /tmp/lint/.automation/test/typescript_standard/typescript_good_1.ts                                                                                                                                                                                                                                                                                                                     2020-10-17 13:12:58 [DEBUG ]   Workspace path: /tmp/lint                                                                                                                                                                                                                                                                     2020-10-17 13:12:58 [DEBUG ]   File: /tmp/lint/.automation/test/typescript_es/typescript_bad_1.ts, FILE_NAME: typescript_bad_1.ts, DIR_NAME:/tmp/lint/.automation/test/typescript_es, FILE_STATUS: bad, INDIVIDUAL_TEST_FOLDER: typescript_es                                                                                2020-10-17 13:12:58 [INFO  ]   ---------------------------                                                                                                                                                                                                                                                                   2020-10-17 13:12:58 [INFO  ]   File:[/tmp/lint/.automation/test/typescript_es/typescript_bad_1.ts]                                                                                                                                                                                                                           2020-10-17 13:12:59 [ERROR ]   Found errors in [eslint] linter!                                                                                                                                                                                                                                                              2020-10-17 13:12:59 [ERROR ]   This file should have failed test case!                                                                                                                                                                                                                                                       2020-10-17 13:12:59 [ERROR ]   Error code: 0. Command run:[$2020-10-17T13:12:58.779Z eslint:cli CLI args: [ '--no-eslintrc', '-c', '/tmp/lint/.github/linters/.eslintrc.yml', '--debug', '/tmp/lint/.automation/test/typescript_es/typescript_bad_1.ts' ]                                                                    2020-10-17T13:12:58.782Z eslint:cli Running on files                                                                                                                                                                                                                                                                         2020-10-17T13:12:58.798Z eslint:config-array-factory Loading YAML config file: /tmp/lint/.github/linters/.eslintrc.yml                                                                                                                                                                                                       2020-10-17T13:12:58.830Z eslint:config-array-factory Loading parser "@typescript-eslint/parser" from /tmp/lint/.github/linters/.eslintrc.yml                                                                                                                                                                                 2020-10-17T13:12:58.834Z eslint:config-array-factory Loaded: @typescript-eslint/parser@3.10.1 (/node_modules/@typescript-eslint/parser/dist/index.js)                                                                                                                                                                        2020-10-17T13:12:59.242Z eslint:config-array-factory Loading plugin "@typescript-eslint" from /tmp/lint/.github/linters/.eslintrc.yml                                                                                                                                                                                        2020-10-17T13:12:59.243Z eslint:config-array-factory Loaded: @typescript-eslint/eslint-plugin@4.4.1 (/node_modules/@typescript-eslint/eslint-plugin/dist/index.js)                                                                                                                                                           2020-10-17T13:12:59.552Z eslint:config-array-factory Plugin /node_modules/@typescript-eslint/eslint-plugin/dist/index.js loaded in: 309ms                                                                                                                                                                                    2020-10-17T13:12:59.553Z eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/tmp/lint', loose: false } ]                                                                                                                                                                    2020-10-17T13:12:59.555Z eslint:ignore-pattern   processed: { basePath: '/tmp/lint', patterns: [ '/**/node_modules/*' ] }                                                                                                                                                                                                    2020-10-17T13:12:59.555Z eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/tmp/lint', loose: false } ]                                                                                                                                                                    2020-10-17T13:12:59.555Z eslint:ignore-pattern   processed: { basePath: '/tmp/lint', patterns: [ '/**/node_modules/*' ] }                                                                                                                                                                                                    2020-10-17T13:12:59.556Z eslint:file-enumerator Start to iterate files: [ '/tmp/lint/.automation/test/typescript_es/typescript_bad_1.ts' ]                                                                                                                                                                                   2020-10-17T13:12:59.558Z eslint:file-enumerator File: /tmp/lint/.automation/test/typescript_es/typescript_bad_1.ts                                                                                                                                                                                                           2020-10-17T13:12:59.558Z eslint:cascading-config-array-factory Load config files for /tmp/lint/.automation/test/typescript_es.                                                                                                                                                                                               2020-10-17T13:12:59.560Z eslint:cascading-config-array-factory Configuration was determined: ConfigArray(2) [ { type: 'config', name: 'DefaultIgnorePattern', filePath: '', criteria: null, env: undefined, globals: undefined, ignorePattern: IgnorePattern { patterns: [Array], basePath: '/tmp/lint', loose: false }, noInlineConfig: undefined, parser: undefined, parserOptions: undefined, plugins: undefined, processor: undefined, reportUnusedDisableDirectives: undefined, root: undefined, rules: undefined, settings: undefined }, { type: 'config', name: '--config', filePath: '/tmp/lint/.github/linters/.eslintrc.yml', criteria: null, env: { browser: true, es6: true, jest: true }, globals: { Atomics: 'readonly', SharedArrayBuffer: 'readonly' }, ignorePattern: undefined, noInlineConfig: undefined, parser: { error: null, filePath: '/node_modules/@typescript-eslint/parser/dist/index.js', id: '@typescript-eslint/parser', importerName: '--config', importerPath: '/tmp/lint/.github/linters/.eslintrc.yml' }, parserOptions: { ecmaVersion: 2018, sourceType: 'module' }, plugins: { '@typescript-eslint': [Object] }, processor: undefined, reportUnusedDisableDirectives: undefined, root: undefined, rules: {}, settings: undefined } ] on /tmp/lint/.automation/test/typescript_es                                                                                                                                                                                                                                                                                                                            2020-10-17T13:12:59.561Z eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/tmp/lint', loose: false } ]                                                                                                                                                                    2020-10-17T13:12:59.561Z eslint:ignore-pattern   processed: { basePath: '/tmp/lint', patterns: [ '/**/node_modules/*' ] }                                                                                                                                                                                                    2020-10-17T13:12:59.562Z eslint:ignore-pattern Check {                                                                                                                                                                                                                                                                         filePath: '/tmp/lint/.automation/test/typescript_es/typescript_bad_1.ts',                                                                                                                                                                                                                                                    dot: false,                                                                                                                                                                                                                                                                                                                  relativePath: '.automation/test/typescript_es/typescript_bad_1.ts',                                                                                                                                                                                                                                                          result: true                                                                                                                                                                                                                                                                                                               }                                                                                                                                                                                                                                                                                                                            2020-10-17T13:12:59.562Z eslint:file-enumerator Complete iterating files: ["/tmp/lint/.automation/test/typescript_es/typescript_bad_1.ts"]                                                                                                                                                                                   2020-10-17T13:12:59.562Z eslint:cli-engine Linting complete in: 6ms                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /tmp/lint/.automation/test/typescript_es/typescript_bad_1.ts                                                                                                                                                                                                                                                                   0:0  warning  File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ✖ 1 problem (0 errors, 1 warning)].                                                                                                                                                                                                                                                                                          2020-10-17 13:12:59 [DEBUG ]   File: /tmp/lint/.automation/test/typescript_es/typescript_good_1.ts, FILE_NAME: typescript_good_1.ts, DIR_NAME:/tmp/lint/.automation/test/typescript_es, FILE_STATUS: good, INDIVIDUAL_TEST_FOLDER: typescript_es                                                                             2020-10-17 13:12:59 [INFO  ]   ---------------------------                                                                                                                                                                                                                                                                   2020-10-17 13:12:59 [INFO  ]   File:[/tmp/lint/.automation/test/typescript_es/typescript_good_1.ts]                                                                                                                                                                                                                          2020-10-17 13:13:00 [INFO  ]    - File:[typescript_good_1.ts] was linted with [eslint] successfully
```

**Comment by ferrarimarco** [comment]
After some digging, I discovered that this happens for good files too! Look at the output of the latest builds

**Comment by ferrarimarco** [comment]
It happens for good files as well, but we were not seeing the output. Warnings are the same! See the last build output.

**Comment by ferrarimarco** [comment]
Ok, I know what's happening! eslint excludes dotfiles and dotfolders by default :(

Let me find a workaround

**Comment by ferrarimarco** [comment]
Fixed by adding a `.eslintignore`.

From the docs:

```
Allowlist and denylist rules specified via --ignore-pattern or .eslintignore are prioritized above implicit ignore rules.

For example, in this scenario, .build/test.js is the desired file to allowlist. Because all Dotfolders and their children are ignored by default, .build must first be allowlisted so that eslint because aware of its children. Then, .build/test.js must be explicitly allowlisted, while the rest of the content is denylisted.
```

**Review by admiralAwkbar — APPROVED** [review]
Hot! Such great fixes

**Comment by GaboFDC** [comment]
@ferrarimarco @admiralAwkbar I think this broke the today release, I'm giving a look, but not sure if is something general or not.

**Comment by ferrarimarco** [comment]
Let's see! I don't find this kind of output in the build logs of this PR :(

**Comment by GaboFDC** [comment]
> 
> 
> Let's see! I don't find this kind of output in the build logs of this PR :(

see https://github.com/GaboFDC/test-super-linter/pull/1/checks?check_run_id=1276960567

**Comment by ferrarimarco** [comment]
@GaboFDC can you set `ACTIONS_RUNNER_DEBUG=true`?

**Comment by GaboFDC** [comment]
https://github.com/github/super-linter/pull/881

**Pull request merged**
