### PR TITLE
Ignore more files from linting

### LINKED ISSUE #985: Ignoring same files locally as when run as an action
When I run this locally (on a Mac) it includes files/folders (like `node_modules`) that are ignored when run through GitHub Actions

What I'm running:

```
docker run -e RUN_LOCAL=true \                                                                                                                   
         -e VALIDATE_ALL_CODEBASE=false \
         -e VALIDATE_HTML=true \
         -v $PWD:/tmp/lint github/super-linter
```

I saw #179 but that seems to be about dynamically ignoring folders - I just want to ignore the files and folders that the super-linter knows to ignore anyway when run as aa GitHub Action.

Am I doing something wrong or is this not supported when it runs locally?

### PR DESCRIPTION
**Pull request by bazzadp**
Fixes #985 

## Proposed Changes

This adds the following folders to the exclusion list when linting the whole workspace:
- `node_modules`
- ~`env` - used by Virtual Env~. Removed after discussion below

It also adds the following files show are binary in nature and so unlikely to ever need to be linted:
- `.DS_Store`
- `.gif`
- `.ico`
- `.jpg`
- `.jpeg`
- `.pdf`
- `.png`
- `.webp`
- `.woff`
- `.woff2`

This makes it a lot faster the build the file list when running the linter locally or in `VALIDATE_ALL_CODEBASE` mode.

### Author/Contributor
- [X] If documentation is needed for this change, has that been included in this pull request - not applicable

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by bazzadp** [comment]
Note the media file exclusions is more to exclude large amounts of useless WARNings like below than for performance reasons:

```
2020-11-17 00:08:16 [INFO]   ---------------------------------
2020-11-17 00:08:16 [INFO]   ------ File list to check: ------
2020-11-17 00:08:16 [INFO]   ---------------------------------
2020-11-17 00:08:16 [WARN]   Failed to get filetype for:[/tmp/lint/.DS_Store]!
2020-11-17 00:08:16 [WARN]   Failed to get filetype for:[/tmp/lint/.github/.DS_Store]!
2020-11-17 00:10:28 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/accessibility/example-of-a-skip-link-on-google.com.png]!
2020-11-17 00:10:28 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/accessibility/example-of-good-and-bad-color-contrast-lookzook.png]!
2020-11-17 00:10:28 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/accessibility/example-of-good-and-bad-color-contrast-lookzook.svg]!
2020-11-17 00:10:28 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/accessibility/fig2.png]!
2020-11-17 00:10:28 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/accessibility/fig3.png]!
2020-11-17 00:10:29 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/accessibility/fig4.png]!
2020-11-17 00:10:29 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/accessibility/fig5.png]!
2020-11-17 00:10:29 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/accessibility/fig6.png]!
2020-11-17 00:10:29 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/accessibility/fig8.png]!
2020-11-17 00:10:29 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/accessibility/fig9.png]!
2020-11-17 00:10:29 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/accessibility/hero_lg.jpg]!
2020-11-17 00:10:29 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/accessibility/hero_lg.webp]!
2020-11-17 00:10:29 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/accessibility/hero_sm.jpg]!
2020-11-17 00:10:29 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/accessibility/hero_sm.webp]!
2020-11-17 00:10:30 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/accessibility/hero_xl.jpg]!
2020-11-17 00:10:30 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/ch16_fig12_header_example_with_cookie.jpg]!
2020-11-17 00:10:30 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/ch16_fig13_cookies_on_cacheable_responses.jpg]!
2020-11-17 00:10:30 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/ch16_fig14_service_worker_adoption.jpg]!
2020-11-17 00:10:30 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/ch16_fig15_lighthouse_example.jpg]!
2020-11-17 00:10:30 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/ch16_fig16_cacheable_responses_set_cookie.jpg]!
2020-11-17 00:10:30 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/ch16_fig1_redbot_example.jpg]!
2020-11-17 00:10:30 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/ch16_fig8_resource_age.jpg]!
2020-11-17 00:10:30 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/fig12.png]!
2020-11-17 00:10:31 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/fig13.png]!
2020-11-17 00:10:31 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/fig14.png]!
2020-11-17 00:10:31 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/fig2.png]!
2020-11-17 00:10:31 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/fig21.png]!
2020-11-17 00:10:31 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/fig22.png]!
2020-11-17 00:10:31 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/fig3.png]!
2020-11-17 00:10:31 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/fig5.png]!
2020-11-17 00:10:31 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/fig6.png]!
2020-11-17 00:10:31 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/fig7.png]!
2020-11-17 00:10:31 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/fig9.png]!
2020-11-17 00:10:32 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/hero_lg.jpg]!
2020-11-17 00:10:32 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/hero_lg.webp]!
2020-11-17 00:10:32 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/hero_sm.jpg]!
2020-11-17 00:10:32 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/hero_sm.webp]!
2020-11-17 00:10:32 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/caching/hero_xl.jpg]!
2020-11-17 00:10:32 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/capabilities/hero_lg.jpg]!
2020-11-17 00:10:32 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/capabilities/hero_lg.webp]!
2020-11-17 00:10:32 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/capabilities/hero_sm.jpg]!
2020-11-17 00:10:33 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/capabilities/hero_sm.webp]!
2020-11-17 00:10:33 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/capabilities/hero_xl.jpg]!
2020-11-17 00:10:33 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/fig1.png]!
2020-11-17 00:10:33 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/fig11.png]!
2020-11-17 00:10:33 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/fig13.png]!
2020-11-17 00:10:33 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/fig15.png]!
2020-11-17 00:10:33 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/fig16.png]!
2020-11-17 00:10:33 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/fig17.png]!
2020-11-17 00:10:33 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/fig18.png]!
2020-11-17 00:10:33 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/fig19.png]!
2020-11-17 00:10:34 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/fig20.png]!
2020-11-17 00:10:34 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/fig22.png]!
2020-11-17 00:10:34 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/fig26.png]!
2020-11-17 00:10:34 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/fig27.png]!
2020-11-17 00:10:34 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/hero_lg.jpg]!
2020-11-17 00:10:34 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/hero_lg.webp]!
2020-11-17 00:10:34 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/hero_sm.jpg]!
2020-11-17 00:10:34 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/hero_sm.webp]!
2020-11-17 00:10:34 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/hero_xl.jpg]!
2020-11-17 00:10:35 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/html_cdn_usage.png]!
2020-11-17 00:10:35 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/html_tls_negotiation_time.png]!
2020-11-17 00:10:35 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/resource_tls_negotiation_time.png]!
2020-11-17 00:10:35 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/subdomain_resource_cdn_usage.png]!
2020-11-17 00:10:35 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/thirdparty_resource_cdn_usage.png]!
2020-11-17 00:10:35 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/use_of_vary.png]!
2020-11-17 00:10:35 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cdn/use_of_vary_on_cdn.png]!
2020-11-17 00:10:35 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cms/cms-logos.png]!
2020-11-17 00:10:35 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cms/fig10.png]!
2020-11-17 00:10:35 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cms/fig11.png]!
2020-11-17 00:10:36 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cms/fig12.png]!
2020-11-17 00:10:36 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cms/fig14.png]!
2020-11-17 00:10:36 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cms/fig16.png]!
2020-11-17 00:10:36 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cms/fig18.png]!
2020-11-17 00:10:36 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cms/fig20.png]!
2020-11-17 00:10:36 [WARN]   Failed to get filetype for:[/tmp/lint/src/static/images/2019/cms/fig21.png]!

```

**Review by ferrarimarco — CHANGES_REQUESTED** [review]
Hi @bazzadp ! Thanks for the PR.

A couple of notes:

1. The `node_modules` exclusion looks fine
1. Virtualenv paths are not mandated in any way ([AFAIK](https://docs.python.org/3/library/venv.html)). Example: The VS Code Python Extension looks in a [number of places](https://code.visualstudio.com/docs/python/environments#_where-the-extension-looks-for-environments). I think it's better to use FILTER_REGEX_EXCLUDE for this.
1. The binary files exclusion is a nice idea. I'm wondering if there's a more generic way of doing that.

In my dotfiles, I used this nice function, checking if Git **thinks** that a file is binary:

```
is_binary() {
    p=$(printf '%s\t-\t' -)
    t=$(git diff --no-index --numstat /dev/null "$1")
    case "$t" in "$p"*) return 0 ;; esac
    return 1
}
```

Can you think about something similar?

Thanks!

**Comment by bazzadp** [comment]
> Virtualenv paths are not mandated in any way (AFAIK). Example: The VS Code Python Extension looks in a number of places. I think it's better to use FILTER_REGEX_EXCLUDE for this.

Oh digging into this more, I see that I'm setting the `env` folder. I'll change this to `.venv` so will be picked up with existing exclusion. Will remove from this PR. Thanks for pointing this out!

BTW `FILTER_REGEX_EXCLUDE` is only semi-useful as it's applied AFTER grabbing the list of files. My issue is that grabbing that file list was very slow - probably mostly due to `node_modules` but thought I'd clean them all up while I was at it. But using `.venv` is a better option.

> The binary files exclusion is a nice idea. I'm wondering if there's a more generic way of doing that. In my dotfiles, I used this nice function, checking if Git thinks that a file is binary:

I do wonder if that test for binary file, on each file presumably, would take more processing time than just having an exclusion list? Annoyingly [`find` doesn't have an executable filter](https://stackoverflow.com/questions/29516984/how-to-find-binary-files-in-a-directory). As I said above, this one is really just to reduce logging noise (and a bit of processing time) as these files are never gonna be linted so think anything we can do here quickly is a good thing but do worry about over complicating it. WDYT?

**Comment by ferrarimarco** [comment]
You've a point actually, about the check. Let me think about this a bit.

PS: I found the `-executable` test for `find`: https://linux.die.net/man/1/find. BTW, this is not applicable, because we also lint shell scripts, which might be executable, and we even have a custom-crafted `bash-exec` linter for that :)

**Comment by ferrarimarco** [comment]
Additionally, we might lower that `warn` to `debug` to have less noise in the log. Which might make sense. @admiralAwkbar thoughts?

**Comment by bazzadp** [comment]
> Additionally, we might lower that `warn` to `debug` to have less noise in the log. Which might make sense. @admiralAwkbar thoughts?

I like that idea! Removes from log, but makes more obvious why in debug mode. Happy to add to this PR and remove others if you wanna go that way.

**Comment by ferrarimarco** [comment]
I think we can still keep the exclusions you listed here :)

I'll create a new issue to discuss about the warn vs debug thing

**Comment by ferrarimarco** [comment]
Ok, I created #1005 to discuss about tuning output. This PR still has value IMHO. Let's separate the streams :)

**Comment by ferrarimarco** [comment]
@bazzadp can you also alphabetically sort the extensions you added? So it's easier to know the spot to add new ones.

**Comment by bazzadp** [comment]
Adding `node_modules` I agree definitely has value, but why bother maintaining a list of static files to ignore if only issue is logging and we agree to move to DEBUG?

Shouldn't we hold this PR for that decision, and then, depending on that decision either include the files to be ignored as is currently there, if decision is not to reducing this logging to DEBUG, or remove them from this PR and reducing the logging to DEBUG instead?

**Comment by bazzadp** [comment]
> @bazzadp can you also alphabetically sort the extensions you added? So it's easier to know the spot to add new ones.

Done.

**Comment by ferrarimarco** [comment]
I still think it might be worth excluding some common binary files (because excluding all might be too heavy, unless we come up with a clever use of `find` to do this).

Let's see what the other maintainers have to say here :)

**Review by tigthor — APPROVED** [review]

**Review by GaboFDC — APPROVED** [review]
I also agree, explicitly ignoring the binaries, rather than something automagically, that may exclude actual code files.
Seems goon enough to me, and we could gather more insights about other binary files with the later usage.

**Review by ferrarimarco — APPROVED** [review]

**Comment by admiralAwkbar** [comment]
@bazzadp @ferrarimarco @GaboFDC great work in here. i agree with it all, you guys are really crushing it out here ;)

**Pull request merged**
