### PR TITLE
adding safe

### PR DESCRIPTION
**Pull request by admiralAwkbar**
- Solve issue with safe workspace

### CODE REVIEW

**Comment by nvuillam** [comment]
Hi neighbor !
I struggled a lot for the same on MegaLinter... the solution (which may not be complete yet) was to add /tmp/lint as safe.directory from within the container (directly in entrypoint.sh)

Good luck !

**Comment by nvuillam** [comment]
@admiralAwkbar  you can check here :) https://github.com/megalinter/megalinter/blob/07c082c2f1af8597cba7b92bcb406a7045ff8c77/entrypoint.sh#L6

**Review by lindluni — DISMISSED** [review]

**Comment by admiralAwkbar** [comment]
@nvuillam your my hero thanks for the info!

**Comment by nvuillam** [comment]
You're welcome, when I saw your commits I saw myself struggling two days ago ... :)
I even looked here to see if you found the solution before me haha ^^

**Comment by nvuillam** [comment]
You may add `git config --global --add safe.directory /github/workspace` for your internal CI jobs ^^

**Pull request merged**
