### PR TITLE
Add Gitleaks for secret scanning

### LINKED ISSUE #1856: Add secretlint
[secretlint](https://github.com/secretlint/secretlint) is that Pluggable linting tool to prevent committing credential.
We can notice the committed credentials by adding them as CI.

How to add secretlint as CI: https://github.com/secretlint/secretlint#ci

### PR DESCRIPTION
**Pull request by massongit**
Fixes #1856

## Proposed Changes
[Gitleaks](https://github.com/zricethezav/gitleaks) is a SAST tool for detecting hardcoded secrets.
We can notice the committed credentials by adding them as CI.

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by JonZeolla** [comment]
Can you comment as to why secretlint was preferred over some of the alternatives?  Personally, I am a fan of https://github.com/zricethezav/gitleaks

**Comment by admiralAwkbar** [comment]
@massongit  @JonZeolla 
Hey, this is great. Im not too picky on what tool we use... from a quick look, it seems `gitleaks` has a much larger following and `secretlint`

Both do seem to allow us to follow our standard of linting a single file at a time. 
Both do offer configuration which is a needed ability in this tool.

Can you guys come to a consensus on which tool we should adopt?

**Comment by massongit** [comment]
Thank you for your propose!
I didn't know about `gitleaks`. However, as far as I read it's README, it seems that it is more versatile than `secretlint`.

**Comment by massongit** [comment]
I think it might be a good idea to use `gitleaks` instead of `secretlint`.

**Comment by admiralAwkbar** [comment]
@massongit @JonZeolla Awesome guys, we can take this current PR and I can help catch the edges that are missed :)

**Comment by JonZeolla** [comment]
One thing to keep in mind is any of these tools can be really noisy and generate false positives.  I suggest including a minimal, high fidelity configuration to start.  I do a lot of tuning of these kind of tools in my day job so I'm happy to review/contribute to that part

**Comment by admiralAwkbar** [comment]
@massongit  @JonZeolla Any help with the `.gitleaks.toml` file is much appreciated

I think I got most of it done

now for testing

**Comment by massongit** [comment]
I removed secretlint related code.

**Comment by massongit** [comment]
@admiralAwkbar 
>Any help with the `.gitleaks.toml` file is much appreciated

How about applying the default configuration ( https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml ) ?

**Pull request merged**
