### PR TITLE
Add support for Azure Resource Manager (ARM) linting with [arm-ttk]

### PR DESCRIPTION
**Pull request by krowlandson**
# Azure Resource Manager (ARM) linting with [arm-ttk]

Hopefully you don't mind me dropping this in... I'm doing some work where I need to validate ARM templates. Rather than running a seperate linter, I've worked on integrating [arm-ttk](https://github.com/azure/arm-ttk) into [Super-Linter](https://github.com/github/super-linter).

I think I've covered off the important elements and maintained consistency with existing approaches / standards. I've also pulled in all latest updates and integrated these with my work too. Please feel free to pass feedback for updates as needed.

Hopefully the rest is fairly self-explanatory.

### CODE REVIEW

**Comment by krowlandson** [comment]
Just to add, I'm not sure what tests you run in the background so please reach out if there's anything which needs fundamentally changing for this to pass all internal checks.

**Comment by krowlandson** [comment]
Will investigate this:

```shell
Successfully found binary for [arm-ttk] in system location: [/usr/bin/arm-ttk]
---------------------------
File:[/tmp/lint/.automation/test/arm/arm_bad_1.json]
 - File:[arm_bad_1.json] failed test case with [arm-ttk] successfully
---------------------------
File:[/tmp/lint/.automation/test/arm/arm_good_1.json]
ERROR! Found errors in [arm-ttk] linter!
ERROR:[/action/lib/worker.sh: line 356: Import-Module: command not found]
ERROR: Linter CMD:[Import-Module /opt/microsoft/arm-ttk/arm-ttk/arm-ttk.psd1 ; $config = $(Import-PowerShellDataFile -Path /action/lib/.automation/.arm-ttk.psd1) ; Test-AzTemplate @config -TemplatePath /tmp/lint/.automation/test/arm/arm_good_1.json]
```

**Comment by krowlandson** [comment]
Sorry, just some quality checks following the TestCodebase fix. That should be me done unless you have any further suggestions for updates or additions.

**Comment by admiralAwkbar** [comment]
@krowlandson That is some amazing work! thank you for all the hard work!
Getting some last tests then pushing

**Comment by krowlandson** [comment]
> @krowlandson That is some amazing work! thank you for all the hard work!
> Getting some last tests then pushing

That's great... thank you for picking this up for integration so quickly! Looking forward to making more use of this in our pipelines 😄 Happy to provide help if any bugs.

**Comment by admiralAwkbar** [comment]
@krowlandson 
Hunting this:
https://github.com/github/super-linter/pull/369/checks?check_run_id=841623259#step:4:79

**Comment by krowlandson** [comment]
> @krowlandson
> Hunting this:
> https://github.com/github/super-linter/pull/369/checks?check_run_id=841623259#step:4:79

Did you catch what was causing this?

**Pull request merged**
