### PR TITLE
Install R directly and don't report npm-groovy-lint usage stats

### LINKED ISSUE #2199: R cannot find a required library
## Describe the bug

Given that we don't fix the dependency versions we install when building the container image, things can break if we build the image at different times. In this case, the R linter cannot find a required dependency. I discovered this while working on #2195 and #2201.

## Expected behavior

Is fixing dependency versions an option? Dependabot doesn't yet support that, even if [there are workarounds](https://github.com/dependabot/dependabot-core/issues/2129#issuecomment-850045595).

## Steps to Reproduce

1. Clone the repository.
1. Build the image: docker build -t super-linter .

## Logs

```
2021-12-01T16:11:20.9475542Z Error in dyn.load(file, DLLpath = DLLpath, ...) : 
2021-12-01T16:11:20.9476501Z   unable to load shared object '/usr/lib/R/library/stringi/libs/stringi.so':
2021-12-01T16:11:20.9477579Z   Error loading shared library libicui18n.so.67: No such file or directory (needed by /usr/lib/R/library/stringi/libs/stringi.so)
2021-12-01T16:11:20.9478984Z Calls: <Anonymous> ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
2021-12-01T16:11:20.9479749Z Execution halted
```

### PR DESCRIPTION
**Pull request by ferrarimarco**
Fixes #2199 

## Proposed Changes

1. Don't depend on https://github.com/assignUser/lintr-lib to install R, and install it directly. This is necessary because otherwise R breaks if the dependencies in https://github.com/assignUser/lintr-lib differ from the ones we install when building our image.
1. Don't report npm-groovy-lint usage stats because it needs a full certificate chain to be in place.

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [x] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by ferrarimarco** [comment]
Ok, now R works, but Groovy doesn't :(

**Comment by ferrarimarco** [comment]
```
2021-12-04 21:51:39 [ERROR]   Found errors in [npm-groovy-lint] linter!
2021-12-04 21:51:39 [ERROR]   Error code: 1. Command output:
------
/tmp/lint/.automation/test/groovy/groovy_good_01.groovy


npm-groovy-lint results in 0 linted files:
┌─────────┬───────────┬─────────────┐
│ (index) │ Severity  │ Total found │
├─────────┼───────────┼─────────────┤
│    0    │  'Error'  │      0      │
│    1    │ 'Warning' │      0      │
│    2    │  'Info'   │      0      │
└─────────┴───────────┴─────────────┘
Unexpected error: unable to get local issuer certificate
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)
------
```

**Comment by ferrarimarco** [comment]
@admiralAwkbar R works now, but npm-groovy-lint doesn't :(

One issue solved, one other pops out.

**Comment by ferrarimarco** [comment]
@dependabot rebase

**Comment by ferrarimarco** [comment]
@admiralAwkbar can you have a look as well? Maybe you know how to fix the error above

**Comment by admiralAwkbar** [comment]
@ferrarimarco  the root of the issue:)

```
--insight                    npm-groovy-lint collects anonymous usage statistics using package https://www.npmjs.com/package/insight. If you do not want to share them, use
                               --no-insight option
```
SInce we don't have a full CA chain, it's mad...

**Pull request merged**
