### PR TITLE
Shell check

### PR DESCRIPTION
**Pull request by admiralAwkbar**
This closes #324 

Ref: https://github.com/github/super-linter/pull/239 and https://github.com/github/super-linter/pull/241
This has been rebased on the current (as of creating) master.

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@nemchik thanks for all the hard work on this

**Comment by nemchik** [comment]
I notice the cleanup failed, which is odd given that it is completely untouched by this PR and seemed to work perfectly fine prior (maybe a fluke?)

Maybe it just needs to rerun?

Also I've got https://github.com/github/super-linter/pull/274 open which does away with the need for cleanup 😄

**Comment by admiralAwkbar** [comment]
@nemchik it is normal when the sha is cloned over, might need a small tweek

**Comment by admiralAwkbar** [comment]
I think Ansible is not working as expected...
```
----------------------------------------------
----------------------------------------------
Testing Codebase [ANSIBLE] files...
----------------------------------------------
----------------------------------------------

Successfully found binary in system
Location:[/usr/bin/ansible-lint]

----------------------------------------------
----------------------------------------------
Testing Codebase [TERRAFORM] files...
----------------------------------------------
----------------------------------------------
```

**Comment by nemchik** [comment]
This should fix the problem
https://github.com/nemchik/super-linter/commit/c5a03cbdbef9d1d659d0acc06b0c3ac6e52ec331
You can merge https://github.com/nemchik/super-linter/commits/fix-shellcheck-errors-merged or cherry pick the commit (only one new one) into this branch.

**Comment by admiralAwkbar** [comment]
@nemchik a had just found it lol

**Comment by nemchik** [comment]
I saw this https://github.com/github/super-linter/pull/329/commits/b1525fa76189574649c8d2ac64b18354dd95d0c8 and didn't want to question it until after this merged in case it was a placeholder for some other logic i'm not privy to lol.

**Comment by nemchik** [comment]
woohoo! passing tests!

**Comment by admiralAwkbar** [comment]
interesting.. still no ansible tests run...

**Comment by admiralAwkbar** [comment]
we should see: 
```
----------------------------------------------
----------------------------------------------
Testing Codebase [ANSIBLE] files...
----------------------------------------------
----------------------------------------------

Successfully found binary in system
Location:[/usr/bin/ansible-lint]
---------------------------
File:[ansible_bad_1.yml]
 - File:[ansible_bad_1.yml] failed test case with [ansible-lint] successfully
---------------------------
File:[ansible_good_1.yml]
 - File:[ansible_good_1.yml] was linted with [ansible-lint] successfully
```
But it's skipping as if the find failed

**Comment by admiralAwkbar** [comment]
This is weird @nemchik 
If i try to recreate the loop it works...
```bash
root@ip-172-31-45-114:/tmp# ./x.sh
+ GITHUB_WORKSPACE=/tmp/clone/super-linter
+ TEST_CASE_FOLDER=.automation/test
+ FILE_EXTENSIONS='.*\.\(yml\|yaml\)$'
+ INDVIDUAL_TEST_FOLDER=ansible
+ mapfile -t LIST_FILES
++ find /tmp/clone/super-linter/.automation/test/ansible -type f -regex '.*\.\(yml\|yaml\)$' '!' -path '/tmp/clone/super-linter/.automation/test/ansible/ghe-initialize/*'
+ for file in ${LIST_FILES[@]}
+ echo 'FILE:[/tmp/clone/super-linter/.automation/test/ansible/ansible_bad_1.yml]'
FILE:[/tmp/clone/super-linter/.automation/test/ansible/ansible_bad_1.yml]
+ for file in ${LIST_FILES[@]}
+ echo 'FILE:[/tmp/clone/super-linter/.automation/test/ansible/ansible_good_1.yml]'
FILE:[/tmp/clone/super-linter/.automation/test/ansible/ansible_good_1.yml]
```
So I'm not sure why the script is failing at this point

**Comment by admiralAwkbar** [comment]
@nemchik added logic to help fail tests when it skips all tests... no more false positives

**Comment by admiralAwkbar** [comment]
lol for some reason it works now...

**Comment by nemchik** [comment]
> lol for some reason it works now...

image

**Pull request merged**
