### PR TITLE
Eslint for json jsonc and json5

### LINKED ISSUE #921: Update .eslintrc.yml to accept jsonc files
**Is your feature request related to a problem? Please describe.**

If you use jsonc files, the linter will complain about comments. But if you use https://www.npmjs.com/package/eslint-plugin-json-format, you will find the support is there to simply ignore the comments. VSCode uses this to lint jsonc files. 

**Describe the solution you'd like**

Super-Linter should match VSCode and update the plugin field, along with anything else needed. Also use regular ESLint for json linting. Typescript is useless in projects that use other languages that read in the json files such as C++.

**Describe alternatives you've considered**

Disable the json linter or create your own linter rules and ensure it actually ignore the comments.

**Additional context**

Prevents Windows Terminal from utilizing the json linter which is one of the primary purposes of Super Linter for that project since there's no C++ linter yet to use.

**Note**
If this is a request to add a new language, after submitting this issue check out [the wiki](https://github.com/github/super-linter/wiki/Adding-new-language-support) for more info on how to accomplish that.

### PR DESCRIPTION
**Pull request by admiralAwkbar**
this closes #921

- We moved away from `jsonlint` in order to use `eslint-plugin-json`
- This allows us to validate :
  - `.json`
  - `.jsonc`
  - `.json5`

This should help solve some of the fun with that

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@ferrarimarco do you think this is solid?
or do you think we should stay with `jsonlint` for pure `json` files?

**Comment by ferrarimarco** [comment]
I had a quick look at NPM stats, and apparently `eslint-plugin-json` is the more widely used (downloaded).

To be honest, I'd keep both linters because:

1. Removing one is a breaking change. If we do this, we should bump the super-linter major version, and be really explicit about this in our changelog/release notes.
2. Are we sure that the checks that jsonlint performs are covered by eslint-plugin-json?

Anyway,  the PR is technically correct.

image

**Comment by admiralAwkbar** [comment]
@ferrarimarco  i agree with you

i updated the logic that files with just `.json` are still linted with **jsonlint**
Files that end with `.jsonc` or `.json5` will now be parsed with **eslint**

**Comment by admiralAwkbar** [comment]
@ferrarimarco seems `dotnet-format` release has a bug and we cant run `dotnet-format --version` lol

```bash
bash-5.1# dotnet-format --version
--version option cannot be combined with other arguments.
```

**Comment by WSLUser** [comment]
Not an expert with linters but probably needs an update to the yaml

**Comment by admiralAwkbar** [comment]
@WSLUser no worries! i figured it out :)

Should be good to go once actions stop acting weird...

**Pull request merged**
