### PR TITLE
Simplify the rules loading logic, plus related fixes

### LINKED ISSUE #852: JavaScript ESLint Issue (And possible solution)
**Describe the bug**
Trying to now use a configuration file with ESLint causes issues. This is probably because the script tries to look for JAVASCRIPT_ES_LINTER_RULES (it's dynamically doing this per language) but in some places some things are still defined as JAVASCRIPT_LINTER_RULES. This causes an issue where it skips over custom rules and uses the `DEFAULT_RULES_LOCATION='/action/lib/.automation'` and says that no eslint custom configuration file is present.

**To Reproduce**
Set everything up like normal. Use JAVASCRIPT_ES_CONFIG_FILE. It will keep using the default one or error out because it cannot find the provided file name in the DEFAULT_RULES_LOCATION

**Expected behavior**
I expect it to load the configuration file correctly, but because of an old naming scheme, some of the javascript environment variables do not get updated.

**Screenshots (and possible solution)**
I feel like these vars should be JAVASCRIPT_ES_LINTER_RULES instead of this, because the default one does not get used anymore, so when a config file is provided, only JAVASCRIPT_ES_[var] will get dynamically updated and not JAVASCRIPT_[var].

JAVASCRIPT_ES is in the languages list, JAVASCRIPT is not.

Screenshot from 2020-10-15 01-41-05

**Additional context**
Screenshot from 2020-10-15 01-46-25

As you can see here it looks for JAVASCRIPT_ES_LINTER_RULES **not** JAVASCRIPT_LINTER_RULES
Screenshot from 2020-10-15 02-50-14

### PR DESCRIPTION
**Pull request by ferrarimarco**
Fixes #852 

## Proposed Changes

1. Dynamically initialize `<LANGUAGE>_LINTER_RULES` variable in `GetLinterRules`, and removed the related static assignment from `linter.sh`. For this to work, I had to add a parameter to `GetLinterRules`, pointing to `DEFAULT_RULES_LOCATION`
1. Fix Javascript and Typescript linter rules variable initialization. Now each linter has it's own variable, so the dynamic initialization introduced in older PRs works.
1. Initialized variables in `GetLinterRules` to point to the paths of the primary and secondary language rules files, to avoid repetitions.
1. Added a check for the existence of the rules file in the cases where we expect it to be there (if the user specified one, or the default one).
1. Enable debug output during CI builds.

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@ferrarimarco Very nice work!

**Comment by ferrarimarco** [comment]
Thanks! There are still a couple of rough edges (tests failing), but I'll fix them :)

**Comment by ferrarimarco** [comment]
@admiralAwkbar should be ok now!

**Review by admiralAwkbar — APPROVED** [review]
amazing work

**Pull request merged**
