### PR TITLE
Add the --ignore-missing-schemas flag to kubeval invocation

### LINKED ISSUE #891: Kubernetes validation should not fail on CRD's
Kubeval validation fails when given a K8 configuration with a custom resource definition. The ignore missing schema flag should be used when running `kubeval`.
https://www.kubeval.com/#crds
```
kubeval --ignore-missing-schemas
```

**To Reproduce**
1. Create a file with a CRD
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
spec:
  hosts:
  - productpage
  http:
  - route:
    - destination:
        host: productpage
        subset: v1
```

2. Run lint

**Expected behavior**
The file should not be validated since it is an unknown Kubernetes type.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by pbstriker38**
- This allows kubernetes CRD definitions to pass validation since they
 do not have a schema present in the Kubernetes OpenAPI specification.

Fixes #891 

## Proposed Changes

1. Add the `--ignore-missing-schemas` flag to the kubeval invocation

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by ferrarimarco** [comment]
Please see the related discussion in #891 before merging this.

**Comment by admiralAwkbar** [comment]
@ferrarimarco Thoughts on adding a flag :
- `KUBEVAL_IGNORE_SCHEMA`: default value false
and then we allow users to pass and enable it? or the other way around... I'm not picky...

**Comment by pbstriker38** [comment]
Flag is good, but should be `KUBEVAL_IGNORE_MISSING_SCHEMAS`

**Comment by ferrarimarco** [comment]
@admiralAwkbar what if we give the chance to personalize **any** linter command? Much like we're doing with linter rule files paths, or `VALIDATE_XXXXX`. Shouldn't be too hard.

If we don't do this, the natural question would be: why this linter is special? :)

Thoughts?

**Comment by admiralAwkbar** [comment]
@ferrarimarco I agree
we shoudl do it for all languages

**Comment by ferrarimarco** [comment]
Let me think about this. In the meantime, let's keep this PR open.

**Comment by ferrarimarco** [comment]
Closing this in favor of the design proposal we're discussing in #987

**Comment by odannyc** [comment]
Is there a workaround for this or solution? Currently I am forced to disable `kubeval` within Superlinter, which is unfortunate.

**Comment by ferrarimarco** [comment]
I think there's no applicable workaround you can apply ATM. Follow #987 for updates. Thanks!

**Pull request closed without merging**
