### PR TITLE
Correct release compare language

### PR DESCRIPTION
**Pull request by zkoppert**
No related issue

## Proposed Changes

- Change language in releases to reference the "previous" release instead of the "latest" since that is not always true

## Readiness Checklist
- [X] Label as `breaking` if this is a large fundamental change
- [X] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nemchik** [comment]
GitHub Actions seemed broken earlier today. If you run the following it should re-push your latest commit and trigger new checks:
```
git commit --amend --no-edit
git push -f
```

**Comment by nemchik** [comment]
I probably didn't need to tell you 😅

**Comment by IAmHughes** [comment]
> GitHub Actions seemed broken earlier today. If you run the following it should re-push your latest commit and trigger new checks:

Just re-ran the checks myself. I'm not aware of any Actions outages today by the way, @nemchik. 🤔

**Comment by nemchik** [comment]
> > GitHub Actions seemed broken earlier today. If you run the following it should re-push your latest commit and trigger new checks:
> 
> Just triggered to re-run the checks myself through the UI. I'm not aware of any Actions outages today by the way, @nemchik. 🤔

Something happened a few hours ago for sure. Every PR in this repo somehow resulted in this https://github.com/github/super-linter/pull/386/checks?check_run_id=842840843
image
Other repos seemed unaffected (including my fork of this repo).

**Comment by IAmHughes** [comment]
> Something happened a few hours ago for sure. Every PR in this repo somehow resulted in this https://github.com/github/super-linter/pull/386/checks?check_run_id=842840843

Hmmmm, yeah really weird. Internally I didn't see any chatter about an outage and our GitHub Status public page doesn't show anything. Weird! I'll re-run jobs that failed in any open PRs 👍

**Pull request merged**
