### PR TITLE
README example: `actions/checkout@master` -> `actions/checkout@v2`

### PR DESCRIPTION
**Pull request by gr2m**

### CODE REVIEW

**Comment by zkoppert** [comment]
> Should we update the workflows in this readme as well?

Yes, that would be good.

**Comment by joshmgross** [comment]
> > Should we update the workflows in this readme as well?
> 
> It looks like this PR is updating the workflow in the readme. Is there another one somewhere you are referring to @joshmgross?

Apologies, I meant the workflows in this repository.
https://github.com/github/super-linter/blob/master/.github/workflows/deploy-PROD.yml#L38
https://github.com/github/super-linter/blob/master/.github/workflows/stack-linter.yml#L38
https://github.com/github/super-linter/blob/master/.github/workflows/deploy-DEV.yml#L41

**Comment by admiralAwkbar** [comment]
@joshmgross I would update them as well
I think there was no reason we were not using v2...

**Comment by zkoppert** [comment]
agreed i will pull this and those changes into a staging branch

**Pull request merged**
