### PR TITLE
feat(config): Add support for LINTER_PATH param

### LINKED ISSUE #161: To override LINTER_PATH
**Is your feature request related to a problem? Please describe.**
Most of the existing repo will already have existing lint rules, and most of them will be placed in root directory of project.

Moving all of them to LINTER_PATH (e.g. .github/linters) wil require either some duplication or breaking exiting way to run lint locally

**Describe the solution you'd like**
To have ability to override this param LINTER_PATH.

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by admiralAwkbar**
To add support for `LINTER_RULES_PATH` param. This will make super-lint more
usable for existing projects, which might have lint rule files in
other locations. The default value is still .github/linters.

Closes #161
Closes #167

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@sayboras Hey can you validate it works as expected?

Seems to have passed all CI and such, but would love another look
thanks!

**Comment by sayboras** [comment]
@admiralAwkbar thanks for your kind help.

I have built the docker image (as the one in CI got removed), and tested with this https://github.com/sayboras/cilium/runs/799725643?check_suite_focus=true. The behavior is as expected.

```
---------------------------------------------
...
  -> Codebase does NOT have file:[./.eslintrc.yml], using Default rules at:[/action/lib/.automation/.eslintrc.yml]
----------------------------------------------
User provided file:[.golangci.yml], setting rules file...
```

**Comment by sayboras** [comment]
Just a quick feedback, I think you guys can make it more contributor friendly by allowing running CI on PR from forked repo :)

**Comment by admiralAwkbar** [comment]
@sayboras we much aware :)
Unfortunately, right now CI will not run on a fork due to security concerns...
Working on making that an easy path to navigate as well :)

**Pull request merged**
