### PR TITLE
Allow to specify Actionlint command line arguments by environment variable

### LINKED ISSUE #1852: Allow to specify command line argument of actionlint
**Is your feature request related to a problem? Please describe.**

[actionlint](https://github.com/rhysd/actionlint) provides `-ignore` option to ignore some errors. This is necessary to ignore some false positives or errors which a user is not interested in. However, super-linter currently does not provide a way to pass command line options to actionlint.

Related issue: https://github.com/rhysd/actionlint/issues/26

**Describe the solution you'd like**

I'd like to have the way to ignore some errors from actionlint. It'd be nice to have some environment variable for it.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by rhysd**
Fixes #1852

## Proposed Changes

1. Add environment variable `$GITHUB_ACTIONS_CLI_OPTIONS` to pass additional command line arguments to `actionlint` command as follows. The default value is `null` (which means passing nothing).
2. Update link to the configuration file document of actionlint.

```yaml
env:
    GITHUB_ACTIONS_CLI_OPTIONS: '-ignore "some error"'
```

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by ferrarimarco** [comment]
There's similar work in #1667 that generalizes this for other linters as well.

**Comment by rhysd** [comment]
@ferrarimarco Great. With your PR, `GITHUB_ACITONS_LINTER_COMMAND_OPTIONS` can pass additional command line arguments, am I correct?

**Comment by admiralAwkbar** [comment]
This is being done in #1667

**Comment by ferrarimarco** [comment]
@admiralAwkbar I think it makes sense to reopen this PR, given that I closed #1667 . It should be relatively easy to rebase on the current maser.

**Pull request closed without merging**
