### PR TITLE
Fix list files function typos

### LINKED ISSUE #704: Super-Linter has started linting node_modules as part of v3.10.0
**Describe the bug**
Just got a dependenabot note about v3.10.0 being released. Linting failed in that pull request due to Super-linter now linting the `node_modules` folders and many npm developers not following our HTML conventions.

Note we do not check in `node_modules`to our repo, however we do generate HTML as part of our build process (which requires `npm install` to have run), so run an HTML Lint on that (see [our workflow here](https://github.com/HTTPArchive/almanac.httparchive.org/actions/runs/247486234/workflow)) and this threw the error, which did not happen on v3.9.4

**To Reproduce**

1. Use a repo that uses node
2. Kick off a full HTML linting (not just changed files) using v3.10.0 but also running `npm install` in the action before.
3. Notice from the log files that all `node_module` HTML files are linted - and many probably failed.

**Expected behavior**
I would expect only my source code to lint - like they did prior to v3.10.0

**Screenshots**
See example log file here: https://github.com/HTTPArchive/almanac.httparchive.org/pull/1282/checks?check_run_id=1094735802

**Additional context**
I presume this is due to #696 and could be fixed with the recently merged #684 ? If so can we have a v3.10.1 or v3.11.0 release with that?

### PR DESCRIPTION
**Pull request by ferrarimarco**
Fixes #704

## Proposed Changes

1. Fix typos in the `find` query when building the list of files to lint.

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by bazzadp** [comment]
Looks like this was broken as part of https://github.com/github/super-linter/commit/6040030c8ac8aa95ceb76b1df4b808f61cabccd8 so should we also fix `lib/buildFileList.sh` as part of this as looks like it had a similar typo in that commit?

**Comment by ferrarimarco** [comment]
I don't see that typo in the latest master in `buildFileList.sh`

**Review by admiralAwkbar — DISMISSED** [review]
sorry

**Comment by bazzadp** [comment]
Note this doesn't fix #704 as discussed in this. But should commit this anyway!

**Comment by admiralAwkbar** [comment]
@bazzadp It does now :)

**Review by admiralAwkbar — APPROVED** [review]

**Pull request merged**
