### PR TITLE
testing versioning

### LINKED ISSUE #490: Unexpected linter update
**Describe the bug**
Linter is running latest v3 tag (v3.4.0) despite being set to `github/super-linter@v3.3.2`.

**To Reproduce**

1. Use `github/super-linter@v3.3.2` in GitHub action.
2. Push code. It is then linted by latest v3 image (v3.4.0 currently).

**Expected behavior**
Linting should run at the version I set it to (v3.3.2).

**Screenshots**
Not applicable

**Additional context**
[Example Run](https://github.com/sebs-scholarship/SSF-Blog/runs/917563851)
I use `github/super-linter@v3.3.2` over `docker://github/super-linter:v3.3.2` for Dependabot updates.
Introduced by #428 / 70f801e

### PR DESCRIPTION
**Pull request by zkoppert**
Fixes #490 

## Proposed Changes

1. Make the action.yml reflect the exact current version instead of only the major version tag.

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by zkoppert** [comment]
running a test with an old version in the action.yml to see if that affects the run.

**Comment by ahmadnassri** [comment]
:crossed_fingers:

**Comment by zkoppert** [comment]
Going to merge this to continue testing. Everybody buckle up. 🧑🏻‍🤝‍🧑🏻 So far everything from the Actions team indicates that if we keep the **EXACT**  version specified in `.github/workflows/stack-linter.yml` and `action.yml` then we should be good to go for any future versions. This is evidenced by the fact that when I specify a version that doesn't yet exist `v.3.14.5`, it errors out.

**Comment by ahmadnassri** [comment]
> everything from the Actions team indicates that if we keep the EXACT version specified in .github/workflows/stack-linter.yml and action.yml

thank you for your efforts, and once you're free, would love an expanstion on this line here, asking for my own Actions :pray:

**Comment by zkoppert** [comment]
@ahmadnassri The actions team told me that Actions feature looks at the actions.yml file associated with any specific version (ie v3.0.0) and if there is a docker image specified, it pulls that down as a part of the action. The problem with the super-linter is that when you go back and look at an old action.yml file from previous versions, they specify a docker image with a tag for v3 which is a moving target. It is a moving target because we were updating the v3 docker label to every new v3.x.x release. So for your actions, you should specify your docker image in your actions.yml file updating it for each release.

**Pull request merged**
