### PR TITLE
Add HTML support to super-linter

### LINKED ISSUE #237: HTMLHint for HTML
**Is your feature request related to a problem? Please describe.**

HTML is not linted currently

**Describe the solution you'd like**

HTMLHint is a great HTML linter with a[ wide-range of useful rules](https://htmlhint.com/docs/user-guide/list-rules) and can be run from CLI. Would be happy to see it added to super-linter.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by terencedignon**
Hi Super-linter team, let me know if I'm missing anything in this pull request. I'm not sure how to run the tests locally, so I'm not sure if the config is 100%. 

Thank you for the great tool, looking forward to using it more in the coming months. 

**question** Thoughts on using https://github.com/htmllint/htmllint-cli instead? HTMLHint isn't super useful when it comes to indentations, whitespace, and so on. Also, the HTMLHint project looks like it is losing support.

Closes #237 

Some notes:
- HTMLHint's repo is the source of the bad example.
- It doesn't seem like it's possible to disable individual lines or files in HTMLHint: https://github.com/htmlhint/HTMLHint/issues/161
- The config file replicates the default values for HTMLHint. I thought adding it would be useful for clarity, but let me know if it is bad practice to dup those.

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@terencedignon Amazing work on this...
Working on making sure all looks and feels right :)

**Comment by terencedignon** [comment]
Thank you so much admiralAwkba@. Love the tool!

**Comment by Shinigami92** [comment]
Hi, I'm a co-maintainer of HTMLHint
I want to let you know that `.htmlhintrc` will not work with `v1.0.0` anymore, because we are currently rewrite the complete configuration structure https://github.com/htmlhint/HTMLHint/issues/279

**Comment by zkoppert** [comment]
Thanks for letting us know @Shinigami92! I created #396 to capture that work to be done.

**Pull request merged**
