### PR TITLE
Update rustfmt with 2021 edition

### PR DESCRIPTION
**Pull request by yanganto**
Update Rust formatting tool with 2021 edition

## Proposed Changes

1. Update README
2. Add flag for 2021 edition of Rustfmt

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by yanganto** [comment]
How can I see the error handling pipeline event?

**Review by admiralAwkbar — APPROVED** [review]

**Comment by admiralAwkbar** [comment]
@yanganto Thanks for the add!

**Comment by ferrarimarco** [comment]
There are no tests in this PR, but we didn't notice :( That's why builds are failing now.

**Comment by yanganto** [comment]
@ferrarimarco This PR just provides new edition option for `rustfmt`, should I add test for this?  If so, please kindly tell me, I am willing to help on this.

**Comment by ferrarimarco** [comment]
Hi @yanganto! No worries, I added them (plus a fix) in #2215

**Pull request merged**
