### PR TITLE
ATTN ALL MAINTAINERS: Remove release drafter and add action.yml step

### LINKED ISSUE #490: Unexpected linter update
**Describe the bug**
Linter is running latest v3 tag (v3.4.0) despite being set to `github/super-linter@v3.3.2`.

**To Reproduce**

1. Use `github/super-linter@v3.3.2` in GitHub action.
2. Push code. It is then linted by latest v3 image (v3.4.0 currently).

**Expected behavior**
Linting should run at the version I set it to (v3.3.2).

**Screenshots**
Not applicable

**Additional context**
[Example Run](https://github.com/sebs-scholarship/SSF-Blog/runs/917563851)
I use `github/super-linter@v3.3.2` over `docker://github/super-linter:v3.3.2` for Dependabot updates.
Introduced by #428 / 70f801e

### PR DESCRIPTION
**Pull request by zkoppert**
Fixes #490

## Proposed Changes

1. Change release process to include a `actions.yml` file change before drafting a release.

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Review by Hanse00 — APPROVED** [review]
Sounds reasonable.

**Comment by ferrarimarco** [comment]
This is an improvement but I'd prefer some more automation around this. Why don't we think about scripting this somehow?

We might work on this workflow: https://github.com/github/super-linter/blob/master/.github/workflows/deploy-RELEASE.yml

**Comment by ferrarimarco** [comment]
@admiralAwkbar

**Comment by zkoppert** [comment]
I agree some scripting to automate this would be great!

**Comment by admiralAwkbar** [comment]
@zkoppert I think I could have a small script pull this out

**Comment by admiralAwkbar** [comment]
@zkoppert @ferrarimarco @Hanse00 @nemchik I have some new code to fix the releases and make this much better. I have been testing in a private repo and will soon bring to here :)

**Comment by Hanse00** [comment]
@admiralAwkbar would that negate the need for this change?

**Pull request merged**
