### PR TITLE
Fix test case workspace_path

### PR DESCRIPTION
**Pull request by GaboFDC**
Fixes #

## Proposed Changes

1. ...
2. ...
3. ...

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Review by admiralAwkbar — APPROVED** [review]
nice catch

**Comment by admiralAwkbar** [comment]
@GaboFDC we have done sooo much to this codebase these last few weeks and thank you for sticking it through.. it's getting better :)

**Comment by GaboFDC** [comment]
No prob I see all the improvements and their value, this just shows we have some gaps in our testings, that we can also give a look to improve. Similar to #529 I think we need a test with "VALIDATE_ALL_CODEBASE: false"

**Comment by GaboFDC** [comment]
Ironically, this PRs is failing because the bug it solves 😆

**Comment by admiralAwkbar** [comment]
@GaboFDC Using admin to unblock

**Comment by ferrarimarco** [comment]
My bad, sowwy :)

**Pull request merged**
