### PR TITLE
Disable flag

### LINKED ISSUE #138: Add Support for disabling errors (info-only runs)
**Is your feature request related to a problem? Please describe.**

I have a repository of legacy markdown files that super-linter would be really useful for. I've also encountered similar situations with other repositories in the past. Sometimes, I'm not looking for a pass/fail, but rather for counts of issues so that I can monitor a trend. 

**Describe the solution you'd like**

I'd love to see an option that doesn't fail the build when a linter doesn't pass -- that surfaces the information but returns an exit code of `0`. This way, I can see the counts for informational purposes, and also verify as I'm getting things into shape that the counts really are dropping. Then, I can turn on the linter for "warnings as errors" essentially. 

**Describe alternatives you've considered**

* Using a different, specific linter that has this option. 
* Attempting to capture the exit code myself
* Not using a linter in my build until I've fixed it up locally.

### PR DESCRIPTION
**Pull request by admiralAwkbar**
Resolves #138. 

* [x] Add environment variable to container
* [x] Update bash script to change exit code

### CODE REVIEW

**Comment by zkoppert** [comment]
Add documentation somewhere?

**Comment by admiralAwkbar** [comment]
@zkoppert was adding it to the `README.md` but wasn't sure if should be referenced anywhere else

**Comment by admiralAwkbar** [comment]
@SeanKilleen thanks for the great addition!

**Comment by admiralAwkbar** [comment]
@zkoppert this is golden... make it so..

**Comment by SeanKilleen** [comment]
Thanks for adding the docs I missed! Glad this is useful.

**Pull request merged**
