### PR TITLE
Add an .editorconfig configuration file

### LINKED ISSUE #965: Add an .editorconfig file?
As we've seen in #954, by not including an `.editorconfig` file, we're not able to run `editorconfig-checker` on the whole code base. (the tests work tho!)

Including one has the benefit of being able to spot more issues, and helps us maintaining a consistent style.

Thoughts?

@admiralAwkbar

### PR DESCRIPTION
**Pull request by ferrarimarco**
## Proposed Changes

Closes #965

1. Propose an `.editorconfig`.
1. Fix linting errors reported by editorconfig-checker.

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by ferrarimarco** [comment]
Nice, so we discovered that https://github.com/pinterest/ktlint supports EditorConfig :)

**Comment by admiralAwkbar** [comment]
@ferrarimarco lol it just seems one after another of tests...

**Comment by ferrarimarco** [comment]
And dotnet-format as well :)

**Comment by ferrarimarco** [comment]
Ok, this should do it

**Review by GaboFDC — APPROVED** [review]

**Pull request merged**
