### PR TITLE
fix output folder for persistance

### LINKED ISSUE #584: Using GitHub Actions no report is found
**Describe the bug**
In GitHub Actions the action outputs that the reports have been generated to a folder.
However the GitHub Actions Artifact Upload can't find any report to upload.

**To Reproduce**

Setup the github action check

```
name: Quality Gate - Super-Linter 

on:
  pull_request:
    branches: [ master, develop ]

jobs:

  quality_check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Super-Linter
      uses: github/super-linter@v3.6.0
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_WORKSPACE: /github/workspace
        OUTPUT_FOLDER: "QualityReports"
        OUTPUT_DETAILS: detailed

    - uses: actions/upload-artifact@v2
      with:
        name: SuperLinter-QualityReport
        path: '${{ github.workspace }}/QualityReports/'
```

Tried changing the the default workspace to several paths and no files were found.

**Expected behavior**
Upload Artifact Action finds and uploads the report generated to the folder defined in OUTPUT_FOLDER

**Screenshots**
image

image

**Additional context**
Super-Linter log

```
Run github/super-linter@v3.6.0
2020-08-18T10:25:33.0297510Z env:
2020-08-18T10:25:33.0298286Z   GITHUB_TOKEN: ***
2020-08-18T10:25:33.0298399Z   DEFAULT_WORKSPACE: /github/workspace
2020-08-18T10:25:33.0298489Z   OUTPUT_FOLDER: QualityReports
2020-08-18T10:25:33.0298577Z   OUTPUT_DETAILS: detailed
2020-08-18T10:25:33.0298649Z ##[endgroup]
2020-08-18T10:25:33.0316934Z ##[command]/usr/bin/docker run --name githubsuperlinterv3_293f91 --label 8118cb --workdir /github/workspace --rm -e GITHUB_TOKEN -e DEFAULT_WORKSPACE -e OUTPUT_FOLDER -e OUTPUT_DETAILS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/PipelinePlayground/PipelinePlayground":"/github/workspace" github/super-linter:v3
2020-08-18T10:25:40.6810670Z --------------------------------------------------------------------------------
2020-08-18T10:25:40.6810869Z 
2020-08-18T10:25:40.6811149Z                               /@@#///////@@/(@//@%/(@.@(       @@
2020-08-18T10:25:40.6811446Z                           @@//////////////////////////////#*  @@@
2020-08-18T10:25:40.6811727Z                         @////@//(///////////@@@@@///@//@/@**//@@(
2020-08-18T10:25:40.6812005Z                       @///////@///////////////@@@@    (           @,
2020-08-18T10:25:40.6812286Z                      @/(&/@////////////////////                     @
2020-08-18T10:25:40.6812406Z                     @////////////////////////@@                      @
2020-08-18T10:25:40.6812525Z                   @%////////(//////////%/////&@            @@       *,@           ______________
2020-08-18T10:25:40.6812651Z              @@@@@/@/#/////(&//////////////////                       .@         /              \
2020-08-18T10:25:40.6812964Z         *@@@@@.    .%///(//@//////////////////&.   .@@,                 @%      / Don't mind me  \
2020-08-18T10:25:40.6813241Z       @@%           .&@&&/@.@//&/////(//////////    @@@@@@@@@         .. &@    / I'm just looking \
2020-08-18T10:25:40.6813561Z     @@%               @@@@@   @&/////////////////#   @/       V  @@/ ,@@@ @   <  for some trash... |
2020-08-18T10:25:40.6813686Z @@@%                   @@@@        .%@@@@//////#@ @   @@         @     .,.     \__________________/
2020-08-18T10:25:40.6813806Z                                           @@@/@(  (@@@@% @/\      %
2020-08-18T10:25:40.6813924Z                                            @@@@(    .     .@@/\   #
2020-08-18T10:25:40.6814035Z                                              @                  %@%
2020-08-18T10:25:40.6814107Z 
2020-08-18T10:25:40.6814367Z --------------------------------------------------------------------------------
2020-08-18T10:25:40.6844122Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   ---------------------------------------------[0m
2020-08-18T10:25:40.6872658Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   --- GitHub Actions Multi Language Linter ----[0m
2020-08-18T10:25:40.6901017Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   ---------------------------------------------[0m
2020-08-18T10:25:40.6930936Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   ---------------------------------------------[0m
2020-08-18T10:25:40.6956058Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   The Super-Linter source code can be found at:[0m
2020-08-18T10:25:40.6989365Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m    - https://github.com/github/super-linter[0m
2020-08-18T10:25:40.7018646Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   ---------------------------------------------[0m
2020-08-18T10:25:40.7047502Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   --------------------------------------------[0m
2020-08-18T10:25:40.7072895Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   Gathering GitHub information...[0m
2020-08-18T10:25:40.7098862Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   Successfully found:[0;37m[GITHUB_SHA][0;34m, value:[0;37m[0381f5afe2d3e14aad226e0b0f6bef6c5e5ffe2c][0m
2020-08-18T10:25:40.7125642Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   Successfully found:[0;37m[GITHUB_WORKSPACE][0;34m, value:[0;37m[/github/workspace][0m
2020-08-18T10:25:40.7153200Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   Successfully found:[0;37m[GITHUB_EVENT_PATH][0;34m, value:[0;37m[/github/workflow/event.json][0;34m[0m
2020-08-18T10:25:40.7604950Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   Successfully found:[0;37m[GITHUB_ORG][0;34m, value:[0;37m[brunomartinsprointelliflo][0m
2020-08-18T10:25:40.8082333Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   Successfully found:[0;37m[GITHUB_REPO][0;34m, value:[0;37m[PipelinePlayground][0m
2020-08-18T10:25:40.8109738Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   Successfully found:[0;37m[GITHUB_TOKEN][0m
2020-08-18T10:25:40.8136858Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   Successfully found:[0;37m[GITHUB_REPOSITORY][0;34m, value:[0;37m[brunomartinsprointelliflo/PipelinePlayground][0m
2020-08-18T10:25:40.8162252Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   Successfully found:[0;37m[GITHUB_RUN_ID][0;34m, value:[0;37m[213457159][0m
2020-08-18T10:25:40.8190132Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   --------------------------------------------[0m
2020-08-18T10:25:40.8222724Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   Gathering user validation information...[0m
2020-08-18T10:25:40.8271925Z [0m2020-08-18 10:25:40 [0;34m[INFO  ][0m   - Validating ALL files in code base...[0m
2020-08-18T10:25:43.2397116Z [0m2020-08-18 10:25:43 [0;33m[WARN  ][0m   [editorconfig-checker]: Failed to get version info for:[0m
2020-08-18T10:25:49.8086180Z [0m2020-08-18 10:25:49 [0;33m[WARN  ][0m   No Ansible base directory found at:[/github/workspace/ansible][0m
2020-08-18T10:25:49.8748024Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   [0m
2020-08-18T10:25:49.8774048Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:49.8801479Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:49.8827545Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   Linting [EDITORCONFIG] files...[0m
2020-08-18T10:25:49.8855948Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:49.8883241Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:49.8942041Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:49.8966673Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   File:[/github/workspace/src/PipelinePlaygroundAPI/Properties/launchSettings.json][0m
2020-08-18T10:25:49.9028676Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m    - File:[0;37m[launchSettings.json][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:49.9076558Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:49.9104251Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   File:[/github/workspace/src/PipelinePlaygroundAPI/WeatherForecast.cs][0m
2020-08-18T10:25:49.9153969Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m    - File:[0;37m[WeatherForecast.cs][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:49.9202127Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:49.9227388Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   File:[/github/workspace/src/PipelinePlaygroundAPI/appsettings.json][0m
2020-08-18T10:25:49.9278537Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m    - File:[0;37m[appsettings.json][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:49.9327980Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:49.9353670Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   File:[/github/workspace/src/PipelinePlaygroundAPI/PipelinePlaygroundAPI.csproj][0m
2020-08-18T10:25:49.9409298Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m    - File:[0;37m[PipelinePlaygroundAPI.csproj][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:49.9461451Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:49.9492814Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   File:[/github/workspace/src/PipelinePlaygroundAPI/Program.cs][0m
2020-08-18T10:25:49.9575561Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m    - File:[0;37m[Program.cs][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:49.9631145Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:49.9656369Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   File:[/github/workspace/src/PipelinePlaygroundAPI/Startup.cs][0m
2020-08-18T10:25:49.9706611Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m    - File:[0;37m[Startup.cs][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:49.9757986Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:49.9790111Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   File:[/github/workspace/src/PipelinePlaygroundAPI/appsettings.Development.json][0m
2020-08-18T10:25:49.9859503Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m    - File:[0;37m[appsettings.Development.json][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:49.9909716Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:49.9936899Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m   File:[/github/workspace/src/PipelinePlaygroundAPI/Controllers/WeatherForecastController.cs][0m
2020-08-18T10:25:49.9992250Z [0m2020-08-18 10:25:49 [0;34m[INFO  ][0m    - File:[0;37m[WeatherForecastController.cs][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:50.0047387Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:50.0077331Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   File:[/github/workspace/src/PipelinePlayground.Logic/PipelinePlayground.Logic.csproj][0m
2020-08-18T10:25:50.0137835Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m    - File:[0;37m[PipelinePlayground.Logic.csproj][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:50.0196924Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:50.0225894Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   File:[/github/workspace/src/PipelinePlayground.Logic/RocketLogic.cs][0m
2020-08-18T10:25:50.0287449Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m    - File:[0;37m[RocketLogic.cs][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:50.0342883Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:50.0370459Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   File:[/github/workspace/src/PipelinePlayground.Logic/SafeVaultLogic.cs][0m
2020-08-18T10:25:50.0426565Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m    - File:[0;37m[SafeVaultLogic.cs][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:50.0508566Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:50.0535692Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   File:[/github/workspace/test/XUnitTestProject/XUnitTestProject.csproj][0m
2020-08-18T10:25:50.0605069Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m    - File:[0;37m[XUnitTestProject.csproj][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:50.0661158Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:50.0692579Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   File:[/github/workspace/test/XUnitTestProject/RocketLogicTest.cs][0m
2020-08-18T10:25:50.0754336Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m    - File:[0;37m[RocketLogicTest.cs][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:50.0812583Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:50.0842599Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   File:[/github/workspace/README.md][0m
2020-08-18T10:25:50.0908409Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m    - File:[0;37m[README.md][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:50.2309972Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:50.2337149Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   File:[/github/workspace/PipelinePlayground.sln][0m
2020-08-18T10:25:50.2399009Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m    - File:[0;37m[PipelinePlayground.sln][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:50.2448895Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:50.2478739Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   File:[/github/workspace/SECURITY.md][0m
2020-08-18T10:25:50.2534591Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m    - File:[0;37m[SECURITY.md][0;34m was linted with [0;37m[editorconfig-checker][0;34m successfully[0m
2020-08-18T10:25:50.4336019Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   [0m
2020-08-18T10:25:50.4362502Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:50.4392896Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:50.4419352Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   Linting [JSON] files...[0m
2020-08-18T10:25:50.4445793Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:50.4472735Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:50.4546699Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:50.4588850Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   File:[/github/workspace/src/PipelinePlaygroundAPI/Properties/launchSettings.json][0m
2020-08-18T10:25:50.6419560Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m    - File:[0;37m[launchSettings.json][0;34m was linted with [0;37m[jsonlint][0;34m successfully[0m
2020-08-18T10:25:50.6471010Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:50.6500762Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   File:[/github/workspace/src/PipelinePlaygroundAPI/appsettings.json][0m
2020-08-18T10:25:50.8304727Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m    - File:[0;37m[appsettings.json][0;34m was linted with [0;37m[jsonlint][0;34m successfully[0m
2020-08-18T10:25:50.8357537Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:50.8387719Z [0m2020-08-18 10:25:50 [0;34m[INFO  ][0m   File:[/github/workspace/src/PipelinePlaygroundAPI/appsettings.Development.json][0m
2020-08-18T10:25:51.0263401Z [0m2020-08-18 10:25:51 [0;34m[INFO  ][0m    - File:[0;37m[appsettings.Development.json][0;34m was linted with [0;37m[jsonlint][0;34m successfully[0m
2020-08-18T10:25:51.0511556Z [0m2020-08-18 10:25:51 [0;34m[INFO  ][0m   [0m
2020-08-18T10:25:51.0539454Z [0m2020-08-18 10:25:51 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:51.0568209Z [0m2020-08-18 10:25:51 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:51.0595552Z [0m2020-08-18 10:25:51 [0;34m[INFO  ][0m   Linting [MARKDOWN] files...[0m
2020-08-18T10:25:51.0621082Z [0m2020-08-18 10:25:51 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:51.0646683Z [0m2020-08-18 10:25:51 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:51.0698628Z [0m2020-08-18 10:25:51 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:51.0726419Z [0m2020-08-18 10:25:51 [0;34m[INFO  ][0m   File:[/github/workspace/README.md][0m
2020-08-18T10:25:51.2829629Z [0m2020-08-18 10:25:51 [0;34m[INFO  ][0m    - File:[0;37m[README.md][0;34m was linted with [0;37m[markdownlint][0;34m successfully[0m
2020-08-18T10:25:51.2878644Z [0m2020-08-18 10:25:51 [0;34m[INFO  ][0m   ---------------------------[0m
2020-08-18T10:25:51.2906612Z [0m2020-08-18 10:25:51 [0;34m[INFO  ][0m   File:[/github/workspace/SECURITY.md][0m
2020-08-18T10:25:51.5047184Z [0m2020-08-18 10:25:51 [0;34m[INFO  ][0m    - File:[0;37m[SECURITY.md][0;34m was linted with [0;37m[markdownlint][0;34m successfully[0m
2020-08-18T10:25:54.2438757Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   /github/workspace/META6.json[0m
2020-08-18T10:25:54.2828615Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   [0m
2020-08-18T10:25:54.2852927Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:54.2878590Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:54.2905196Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   Linting [YAML] files...[0m
2020-08-18T10:25:54.2930473Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:54.2954765Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:54.3122282Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:54.3148084Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:54.3173668Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   Generated reports:[0m
2020-08-18T10:25:54.3202777Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:54.3232037Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:54.3261169Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   Reports generated in folder /github/workspace/QualityReports[0m
2020-08-18T10:25:54.3288105Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:54.3314312Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:54.3340547Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   The script has completed[0m
2020-08-18T10:25:54.3367658Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:54.3395165Z [0m2020-08-18 10:25:54 [0;34m[INFO  ][0m   ----------------------------------------------[0m
2020-08-18T10:25:55.4191787Z [0m2020-08-18 10:25:55 [0;32m[NOTICE][0m   All file(s) linted successfully with no errors detected[0m
2020-08-18T10:25:55.4219563Z [0m2020-08-18 10:25:55 [0;34m[INFO  ][0m   ----------------------------------------------[0m
```

### PR DESCRIPTION
**Pull request by admiralAwkbar**
This closes #584 

We need to set the output generated folder for persistence when it defaulted to `DEFAULT_WORKSPACE`

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@brunomartinspro
Tested and fixed it... seems the default was trying to drop in `/tmp/lint` which is not a persistent folder.... so it could never see the files. Now it defaults to `github.workspace` and you can pull the files from the next action... Shipped...

**Comment by brunomartinspro** [comment]
> @brunomartinspro
> Tested and fixed it... seems the default was trying to drop in `/tmp/lint` which is not a persistent folder.... so it could never see the files. Now it defaults to `github.workspace` and you can pull the files from the next action... Shipped...

Wow that was fast! Thanks!

**Comment by brunomartinspro** [comment]
@admiralAwkbar how can i use the latest change? i see that the latest docker image was deployed but the action seems to be referring to the v3 tag.

https://github.com/github/super-linter/blob/master/action.yml

**Comment by admiralAwkbar** [comment]
@brunomartinspro you can use `docker://github/super-linter:latest` or you could wait for later today hopefully and we will push a new release...

**Comment by brunomartinsprointelliflo** [comment]
> @brunomartinspro you can use `docker://github/super-linter:latest` or you could wait for later today hopefully and we will push a new release...

Thanks!

**Comment by brunomartinspro** [comment]
> @brunomartinspro you can use `docker://github/super-linter:latest` or you could wait for later today hopefully and we will push a new release...

Thanks!

**Pull request merged**
