### PR TITLE
Move FILTER_REGEX_INCLUDE and FILTER_REGEX_EXCLUDE test

### PR DESCRIPTION
**Pull request by puggan**
Move FILTER_REGEX_INCLUDE AND FILTER_REGEX_EXCLUDE test before checking filetype

Fixes #
* Removes "Failed to get filetype"-warnings for excluded files

## Proposed Changes
1. Use the filter for include/exclude earlier, to avoid warnings on excluded files.

## Readiness Checklist
* Have not tested the code, is there some automated test when I add a PR?

### Author/Contributor
- [X] If documentation is needed for this change, has that been included in this pull request
Don't think the documentation need updating.

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
Should speed up the test, and generate less unwanted warnings.
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`
enhancement & performance

### CODE REVIEW

**Comment by ferrarimarco** [comment]
Thanks for the PR @puggan !

@admiralAwkbar do we want to tune the `find` clauses we have [here](https://github.com/github/super-linter/blob/master/lib/functions/buildFileList.sh#L96)?

**Comment by admiralAwkbar** [comment]
@ferrarimarco That would likely be a good idea! I like the fixes!

**Comment by ferrarimarco** [comment]
@puggan can you kindly give the suggestion a try? Thanks!

**Comment by puggan** [comment]
I'm not experinced enough with bash to do that, the modification in that I did in this pr as at the border of what I can handle in bash.

**Comment by ferrarimarco** [comment]
Can you allow commits from maintainers on this PR? So that we can push new commits to the same branch you created the PR from. Thanks!

**Comment by puggan** [comment]
"allow commits from maintainers", I have no problem to give access to my fork, is there a easy way to do "allow commits from maintainers", or do I need to find a list, and invite them one and one?

**Comment by ferrarimarco** [comment]
Allow commits from maintainers should do it :) Thanks!

**Comment by GaboFDC** [comment]
> Thanks for the PR @puggan !
> 
> @admiralAwkbar do we want to tune the `find` clauses we have [here](https://github.com/github/super-linter/blob/master/lib/functions/buildFileList.sh?rgh-link-date=2020-11-23T08%3A22%3A12Z#L96)?

I think your link is now wrong? for this cases is better to link to the sha instead of the beach, so the link keeps valid.

I assume you mean to change the find in where we map the whole workspace path? to have the same excludes and includes? I think if we move those filters there if will be the best, also that would solve #907

**Comment by ferrarimarco** [comment]
@GaboFDC I didn't understand your comment LOL :)

**Comment by GaboFDC** [comment]
> @GaboFDC I didn't understand your comment LOL :)

The original link is wrong now, because it points to the branch, and as the code changes the line numbers also change so now the link points to the `# print header #` comment. For these cases is useful to point to the commit sha, so the link stays valid even if the branch changes.

I'm asking if what you meant was to change the `find` we use to map all the files ([here](https://github.com/github/super-linter/blob/44c24cf412a9294773ee5e90bcb52aa1344d8960/lib/functions/buildFileList.sh#L117)) to do the include and exclude regexes there?

**Comment by ferrarimarco** [comment]
@GaboFDC yes, that was what I meant!

**Comment by ferrarimarco** [comment]
Do you think this is worth exploring, or this PR is good as it is? @admiralAwkbar @GaboFDC

**Review by admiralAwkbar — APPROVED** [review]

**Comment by admiralAwkbar** [comment]
@puggan @ferrarimarco I dig this

\Cleaning up out here :)

**Pull request merged**
