### PR TITLE
adding vue to eslint

### LINKED ISSUE #669: How can I handle .vue files linting ?
Hi guys.

In my project I use Vuejs as a frontend framework and I'd like to be able to lint `.vue` files.
The thing is there are :

`<template></template>` which is HTML
`<script></script>` which is Javascript
`<style></style>` which is CSS

in `.vue` files.

How can I make them being linted by Github Super Linter ?

### PR DESCRIPTION
**Pull request by admiralAwkbar**
- This closes #669
- Adding `.vue` files to eslint for linting

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@laurent-brisbois

Can you validate the container works as expected with `.vue` files?
Again, this language is out of my wheelhouse :)

**Comment by laurent-brisbois** [comment]
@admiralAwkbar 
Sure I will test this evening and let you know :-)

**Comment by laurent-brisbois** [comment]
@admiralAwkbar 
Wanted to test it yesterday but didn't have time. I'll try it ASAP.

**Comment by admiralAwkbar** [comment]
@laurent-brisbois Any luck?

**Comment by laurent-brisbois** [comment]
@admiralAwkbar some spare time tonight 100% sure you'll have a feedback 😉

**Comment by laurent-brisbois** [comment]
@admiralAwkbar 
I tried with :
`VALIDATE_ALL_CODEBASE: true` and `VALIDATE_JAVASCRIPT_ES` and I didn't see any .vue file linting in the logs.
Do I have to add any extra configuration ? Or to test in a particular way ?

**Comment by admiralAwkbar** [comment]
@laurent-brisbois Can you give me an example file of good code and bad code, then i can add to this branch and we can test in here?

**Comment by laurent-brisbois** [comment]
@admiralAwkbar I'm preparing that asap.

**Comment by wrux** [comment]
@admiralAwkbar Can this pull request get re-opened? It seems like a useful feature

**Comment by admiralAwkbar** [comment]
@wrux it's still open, I just don't have the knowledge on vue to finish the testing and make any minor updates
Do you have the experience to help with it?

**Comment by wrux** [comment]
@admiralAwkbar sure, I can test it on a project i'm working on. Is is possible to just change the workflow file to point to the branch? `uses: github/super-linter@Vue` I'm not too familiar with actions.

**Comment by GaboFDC** [comment]
> @admiralAwkbar sure, I can test it on a project i'm working on. Is is possible to just change the workflow file to point to the branch? `uses: github/super-linter@Vue` I'm not too familiar with actions.
Yes, you can point to specific branch, tag or even commit with something like `uses: GaboFDC/super-linter@gf_fix_testcase_change`

**Comment by admiralAwkbar** [comment]
In other test cases, i have published to docker hub, and then updated my repo to point to that experimental version for testing.

**Review by akkarapon26 — APPROVED** [review]

**Review by akkarapon26 — APPROVED** [review]

**Review by akkarapon26 — APPROVED** [review]

**Review by Jayson29-undroid — APPROVED** [review]

**Review by Jayson29-undroid — APPROVED** [review]

**Review by Jayson29-undroid — APPROVED** [review]

**Review by Jayson29-undroid — APPROVED** [review]

**Review by Jayson29-undroid — APPROVED** [review]

**Review by tigthor — DISMISSED** [review]

**Review by nbatien1984 — APPROVED** [review]

**Comment by bra1n** [comment]
Is this till being worked on? I've also run into issues with super linter not linting .vue files.

**Comment by laurent-brisbois** [comment]
I think the PR is waiting for more answers from code owners.

**Comment by bra1n** [comment]
It also seems to require an update due to merge conflicts. @admiralAwkbar

**Comment by zkoppert** [comment]
I can take a look at the merge conflicts... 👀

**Comment by zkoppert** [comment]
I believe this is ready for some testing again if @bra1n, @laurent-brisbois, or others who have some vue experience can test this  branch out on some vue code.

**Comment by admiralAwkbar** [comment]
closing from lack of support

**Pull request closed without merging**
