### PR TITLE
Add basic Raku support

### PR DESCRIPTION
**Pull request by nbrown**
Adding support for the language `Raku`
- https://rakubrew.org/

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@nbrown Amazing work.

One fix?
Can you set it to install in `/usr/bin/` instead of `root`

Other than that it seems great!

**Comment by admiralAwkbar** [comment]
Can you also use the installer from https://rakubrew.org/perl/rakubrew instead of the other one that says deprecated?

**Comment by nbrown** [comment]
I think I fixed both of your comments. Please let me know if there's anything else you'd like me to look at.

**Comment by admiralAwkbar** [comment]
@nbrown amazing work! thank you so much for the contributions!

**Pull request merged**
