### PR TITLE
Install, configure, and run jscpd. Add missing tests

### PR DESCRIPTION
**Pull request by ferrarimarco**
## Proposed Changes

1. Install and run [jscpd](https://github.com/kucherenko/jscpd)
1. Add OpenAPI files in YAML format. Previously, we were considering only JSON.
1. Fix the test validation logic. Now the test suite raises a fatal error if we don't add any test for a linter. We already had this check in place, but it was not firing in the case that the file list for a linter was empty.
1. Thanks to the test validation fix, I discovered that we were missing some tests, which I added in this PR:
    1. JSX
    1. OpenAPI
    1. TSX

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by ferrarimarco** [comment]
This PR is completed, but I suspect that having jscpd run on single files kind of defeats part of its purpose, because analysis is limited to single files. Looks like another potential case for #225

**Review by GaboFDC — APPROVED** [review]
JSCPD seems pretty nice. And we keep improving the tests 👍 💯

**Comment by GaboFDC** [comment]
@ferrarimarco some of the "good" files are filing because JSCPD found duplicated code 😂

**Comment by ferrarimarco** [comment]
LOL let me have a look

**Comment by ferrarimarco** [comment]
Let me convert this back to draft while I look after the duplicates in a separate branch

**Comment by ferrarimarco** [comment]
Thanks @GaboFDC for pushing this!

**Comment by GaboFDC** [comment]
@ferrarimarco no prob, I just did the busy work to rebase and update it. Thanks for the original idea and all the work, seems like a nice improvement.
Also made #1137 to remove duplicated code, could appreciate a look over there.

**Comment by KazumaNo** [comment]
You have been invited to the following event.

Title: Re: [github/super-linter] Install, configure, and run jscpd. Add  
missing tests (#1032)











Get Outlook for Asl&nbsp;ndroid and me

**Comment by monstro805** [comment]
how do we fix

**Review by admiralAwkbar — APPROVED** [review]
your amazing

**Comment by admiralAwkbar** [comment]
@ferrarimarco All good!

**Comment by ferrarimarco** [comment]
Thanks for pushing this. I'll give a look at the failing tests.

**Comment by GaboFDC** [comment]
I think this is ready

**Pull request merged**
