### PR TITLE
Add actionlint

### LINKED ISSUE #1771: Add actionlint
[actionlint](https://github.com/rhysd/actionlint) is a static checker for GitHub Actions workflow files.
If we add it, we can find mistakes in GitHub Action workflow files and shell scripts in the files.

### PR DESCRIPTION
**Pull request by massongit**
Fixes #1771

## Proposed Changes

* Add [actionlint](https://github.com/rhysd/actionlint) as static checker for GitHub Actions workflow files.

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@massongit lol we were working on this at the same time... #1775

**Comment by apisTrg93** [comment]
[]()

**Comment by admiralAwkbar** [comment]
@massongit pulling in your code to my branch

**Comment by massongit** [comment]
Thank you for pulling in my code!

**Pull request closed without merging**
