### PR TITLE
Better pwsh module validation

### LINKED ISSUE #925: v3.13.3 is not in Docker Hub, nor GitHub Container Registry
**Describe the bug**

Version 3.13.3 was not deployed to any artifact repository because the [build failed](https://github.com/github/super-linter/runs/1294033734). I've seen the build failing many times because of this exact issue. Time to fix it? :)

**To Reproduce**

1. `docker run ghcr.io/github/super-linter:v3.13.2`

**Expected behavior**

Run `ghcr.io/github/super-linter:v3.13.2`.

**Logs**

```shell
"super-linter": Error response from daemon: name unknown
```

**Additional context**

Complete build log: https://github.com/github/super-linter/runs/1294033734

Relevant extract:

```shell
Step 41/76 : RUN wget --tries=5 -O phive.phar https://phar.io/releases/phive.phar     && wget --tries=5 -O phive.phar.asc https://phar.io/releases/phive.phar.asc     && gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79     && gpg --verify phive.phar.asc phive.phar     && chmod +x phive.phar     && mv phive.phar /usr/local/bin/phive     && rm phive.phar.asc     && phive install --trust-gpg-keys 31C7E470E2138192,CF1A108D0E7AE720,8A03EA3B385DBAA1
 ---> Running in 29bc54cc3eed
Connecting to phar.io (188.94.27.6:443)
Connecting to github.com (140.82.114.4:443)
Connecting to github-production-release-asset-2e65be.s3.amazonaws.com (52.216.102.91:443)
saving to 'phive.phar'
phive.phar           100% |********************************|  187k  0:00:00 ETA
'phive.phar' saved
Connecting to phar.io (188.94.27.6:443)
Connecting to github.com (140.82.112.3:443)
Connecting to github-production-release-asset-2e65be.s3.amazonaws.com (54.231.120.219:443)
saving to 'phive.phar.asc'
phive.phar.asc       100% |********************************|   854  0:00:00 ETA
'phive.phar.asc' saved
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: Address not available
The command '/bin/sh -c wget --tries=5 -O phive.phar https://phar.io/releases/phive.phar     && wget --tries=5 -O phive.phar.asc https://phar.io/releases/phive.phar.asc     && gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79     && gpg --verify phive.phar.asc phive.phar     && chmod +x phive.phar     && mv phive.phar /usr/local/bin/phive     && rm phive.phar.asc     && phive install --trust-gpg-keys 31C7E470E2138192,CF1A108D0E7AE720,8A03EA3B385DBAA1' returned a non-zero code: 2
2020-10-22 17:38:46 [FATAL ]   failed to [build] Dockerfile!
Error: Process completed with exit code 1.
```

Possible workaround, as discussed in https://github.com/nodejs/docker-node/issues/380#issuecomment-348464695

Instead of just running:

```shell
gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
```

use something like:

```shell
( gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$GPG_KEYS" \
  || gpg --keyserver pgp.mit.edu --recv-keys "$GPG_KEYS" \
  || gpg --keyserver keyserver.pgp.com --recv-keys "$GPG_KEYS" )
```

Thoughts?

### LINKED ISSUE #930: Latest image fails on 'Failed to find module'
**Describe the bug**
When running the latest image, linting constantly failes with the message `Failed to find module`

**To Reproduce**

I use this in my repos to run super linter:
```yaml
      - name: Super Linter
        uses: docker://github/super-linter:latest
        env:
          VALIDATE_YAML: true
          VALIDATE_DOCKER: false #bug
```

**Expected behavior**
Shouldn't fail

**Screenshots**
Log:
```
2020-10-30 21:17:01 [INFO  ]   Gathering GitHub information...
2020-10-30 21:17:01 [INFO  ]   Successfully found:[GITHUB_SHA], value:[...]
2020-10-30 21:17:01 [INFO  ]   Successfully found:[GITHUB_WORKSPACE], value:[/github/workspace]
2020-10-30 21:17:01 [INFO  ]   Successfully found:[GITHUB_EVENT_PATH], value:[/github/workflow/event.json]
2020-10-30 21:17:01 [INFO  ]   Successfully found:[GITHUB_ORG], value:[...]
2020-10-30 21:17:01 [INFO  ]   Successfully found:[GITHUB_REPO], value:[...]
2020-10-30 21:17:01 [INFO  ]   Successfully found:[GITHUB_TOKEN]
2020-10-30 21:17:01 [INFO  ]   Successfully found:[GITHUB_REPOSITORY], value:[.../...]
2020-10-30 21:17:01 [INFO  ]   Successfully found:[GITHUB_RUN_ID], value:[...]
2020-10-30 21:17:01 [INFO  ]   --------------------------------------------
2020-10-30 21:17:01 [INFO  ]   Gathering user validation information...
2020-10-30 21:17:01 [INFO  ]   - Validating ALL files in code base...
2020-10-30 21:17:03 [FATAL ]   Failed to find module.
```
**Additional context**
Nothing really

### PR DESCRIPTION
**Pull request by GaboFDC**
Fixes #925
Fixes #930

## Proposed Changes

1. Only validate powershell modules when linting powershell. Not need to fail the build if we are not going to use it
2. Improve logic for validating powershell modules, prevous logic had lines that will never be reached.

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by ferrarimarco** [comment]
@GaboFDC question: why don't we check these powershell modules when we build the image? Those should be present at build time. So we don't have to validate at runtime!

WDYT?

**Comment by ferrarimarco** [comment]
I had this idea after checking the code in `validation.sh`. The `ValidatePowershellModules` function is the only one that deals with checking if libs/executables are there. The rest is to check the values of environment variables, which makes sense.

**Comment by ferrarimarco** [comment]
By moving the check when we build the image, we can fail way faster!

**Comment by GaboFDC** [comment]
Done, but we won't be able to push the fix until the problem with the powershell modules resolves. :(

**Comment by ferrarimarco** [comment]
Nice work!

**Comment by admiralAwkbar** [comment]
@GaboFDC @ferrarimarco 
the root of the issue stems from here:
https://github.com/PowerShell/PowerShellGallery/issues/135

**Comment by admiralAwkbar** [comment]
Once they fix it, we should be good to build again

**Comment by GaboFDC** [comment]
Could we at least push a working image (the prevous version) as the latest to fix the issue?
This is what I meant by not pushing broken build on the issue :)

**Comment by ferrarimarco** [comment]
@GaboFDC @admiralAwkbar can we try again now? https://github.com/PowerShell/PowerShellGallery/issues/135 is reported as mitigated now. Thanks!

**Comment by GaboFDC** [comment]
Done, I reworked it, please give it a look.

**Comment by ferrarimarco** [comment]
Checking the log. There are a couple of issues:

```shell
2020-10-31 01:54:16 [INFO]   Successfully found version for [checkstyle]: /action/lib/linterVersions.sh: line 73: java -jar /usr/bin/checkstyle: No such file or directory
....
2020-10-31 01:54:18 [INFO]   Successfully found version for [golangci-lint]: Error: unknown flag: --version Usage:   golangci-lint [flags]   golangci-lint [command]  Available Commands:   cache       Cache control and information   completion  Output completion script   config      Config   help        Help   linters     List current linters configuration   run         Run this tool in cloud on every github pull request in https://golangci.com for free (public repos)   version     Version  Flags:       --color string              Use color when printing; can be 'always', 'auto', or 'never' (default "auto")   -j, --concurrency int           Concurrency (default NumCPU) (default 2)       --cpu-profile-path string   Path to CPU profile output file   -h, --help                      help for golangci-lint       --mem-profile-path string   Path to memory profile output file       --trace-path string         Path to trace output file   -v, --verbose                   verbose output  Use "golangci-lint [command] --help" for more information about a command.  failed executing command with error unknown flag: --version
```

**Review by admiralAwkbar — APPROVED** [review]

**Comment by ferrarimarco** [comment]
@admiralAwkbar thanks for merging. The issue I reported above about the failed versions are still there. I'll open a separate issue so we don't forget to fix that.

**Comment by admiralAwkbar** [comment]
@ferrarimarco Your the best and thank you!

**Pull request merged**
