### PR TITLE
Remove unneeded variables and eval the rest

### PR DESCRIPTION
**Pull request by ferrarimarco**
Related to #760 

## Proposed Changes

1. Remove the assignment of `VALIDATE_XXXXX` variables. Those variables are not needed because they are set in `validation.sh` anyway. By removing those variables, we don't have to remember to add new ones when extending super-linter to add new languages, and we have to update the the `LANGUAGE_ARRAY` array only.
1. Define and export `ERRORS_XXXX` variables dynamically in `validation.sh`, based on the values in `LANGUAGE_ARRAY`, so that we don't have to define a new `ERRORS_XXXX` variable for each linter we add.
1. Move the initialization of debug and log variables at the top of `linter.sh`, so that we can use logging in sourced files and during the initialization of `linter.sh`.
1. Remove the initialization of such variables from the `Dockerfile` as well, because they are not needed during the build and might confuse the users.

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@ferrarimarco This is amazing... i didnt know you could do that lol

**Comment by admiralAwkbar** [comment]
@ferrarimarco It also seems to skip all runs... check out https://github.com/github/super-linter/pull/781/checks?check_run_id=1178767786

Seems to see no languages and skips all

**Comment by ferrarimarco** [comment]
Will have a look ASAP!

**Comment by ferrarimarco** [comment]
I think tests are running fine, judging from the execution time of that step. There must be something with log settings. I'm checking now.

**Comment by ferrarimarco** [comment]
Should be fixed now. Let's see.

**Comment by ferrarimarco** [comment]
@admiralAwkbar shall we take the chance to remove variables from the `Dockerfile` as well? Why do we need them there if we set defaults or load values from the runtime environment?

**Comment by admiralAwkbar** [comment]
@ferrarimarco I'm trying to understand. I thought it was necessary to add them to the docker container. and it may be needed for users who are running this locally.
That's my fear of removing them from the docker container
but the rest seems to make sense.

**Comment by admiralAwkbar** [comment]
@ferrarimarco It seems to be working as expected and this did seem to clean up a lot of the issues we normally see! pretty cool

**Comment by ferrarimarco** [comment]
I suppose it might do the opposite, meaning: it might confuse users. The [ENV](https://docs.docker.com/engine/reference/builder/#env) directive does (quoting from the docs):

```
The ENV instruction sets the environment variable <key> to the value <value>. This value will be in the environment for all subsequent instructions in the build stage and can be replaced inline in many as well.

[...]

The environment variables set using ENV will persist when a container is run from the resulting image. You can view the values using docker inspect, and change them using docker run --env <key>=<value>.

Environment variable persistence can cause unexpected side effects. For example, setting ENV DEBIAN_FRONTEND=noninteractive changes the behavior of apt-get, and may confuse users of your image.

If an environment variable is only needed during build, and not in the final image, consider setting a value for a single command instead

[...]
```

So I guess we don't need those variables in the Dockerfile. Why would we want to set up during build time like that? We don't care about those values when building the image.

**Comment by admiralAwkbar** [comment]
@ferrarimarco I think your right! i think some additional tests and we can knock this out

**Comment by ferrarimarco** [comment]
I've pushed a new commit to remove those vars as well. Let's see what the testing suite has to say :)

**Review by admiralAwkbar — APPROVED** [review]
Send it

**Pull request merged**
