### PR TITLE
Upgrade npm-groovy-lint@7.2.0 and sql-lint@0.0.15

### LINKED ISSUE #538: Development: Unable to perform npm install in dependencies folder
**Describe the bug**
There is a crash in sql-lint post install task when performing `npm install` in dependencies folder
Env: Windows 10 + Git Bash

**To Reproduce**
1. Clone master branch
2. cd dependencies
3. npm install

**Expected behavior**
npm install should work :)

**Screenshots**
image

### PR DESCRIPTION
**Pull request by nvuillam**
Fixes #538 

- Upgrade dependency to npm-groovy-lint@7.2.0 : it has better performances
- Upgrade dependency to sql-lint@0.0.15 : npm install works on Windows (after fix of https://github.com/joereynolds/sql-lint/issues/157 )

## Proposed Changes

Only the fixes upper

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer 
- [x] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nemchik** [comment]
> I develop on Windows, and I need to upgrade npm-groovy-lint version (i released a better and faster one 🤓)
>
> To do that, I just forked the repo then run `npm install npm-groovy-lint --save` , but as it crashes because of install of sql-lint, I can't :)
>
> I could manually update package.json, but I have no idea about how to update package-lock.json without risking of breaking something 😇

_Originally posted by @nvuillam in https://github.com/github/super-linter/issues/538#issuecomment-671491312_

Just want to confirm, you used npm to get the package.json and package-lock.json updated? (only questioning to confirm, since you had mentioned being unfamiliar)

**Comment by nvuillam** [comment]
I used npm to upgrade npm packages yes :)

I am very familiar with npm but I never had to write manually a package-lock.json, it's just that part I'm unfamiliar about 🤓

**Comment by admiralAwkbar** [comment]
@nvuillam going to add the updates for config file to this as well
since .15 now supports config file, we will need to update the calls and add doc on using config... then we should be good to go

**Comment by nvuillam** [comment]
@admiralAwkbar do you know who added sql-lint ?
Maybe I can provide him/her access on my fork to update the PR ?

**Pull request merged**
