### PR TITLE
trying to create diagram

### PR DESCRIPTION
**Pull request by admiralAwkbar**
- Creating repo diagram for fun

### CODE REVIEW

**Comment by ferrarimarco** [comment]
@admiralAwkbar I don't know if you noticed, but the diagram is not displayed in the README. :(

**Comment by admiralAwkbar** [comment]
I just looked and it was working for me... Not sure if I have some auth...

**Comment by ferrarimarco** [comment]
Also @admiralAwkbar I think we need to limit when the repo visualization workload runs because it's causing some builds to fail

**Comment by admiralAwkbar** [comment]
Hey! Lol I forgot it was only going to be weekly and was testing it... Then actions was messing up and I forgot... Will update

**Comment by ferrarimarco** [comment]
btw I get a 403 when trying to display the image :)

**Pull request merged**
