### PR TITLE
Build image locally for dev

### PR DESCRIPTION
**Pull request by nemchik**
This should eliminate the need to pull into local branches for CI.

### CODE REVIEW

**Comment by nemchik** [comment]
This differs from https://github.com/github/super-linter/pull/273 in that it builds the linter image in CI so that changes to the linter itself can be tested where https://github.com/github/super-linter/pull/273 only uses the released linter from docker hub without any changes that may have been implemented in the branch.

**Comment by nemchik** [comment]
To be honest I now see that the Stack linter check is required/expected so it might make sense to rebase this onto #273 or to rewrite the Stack linter workflow to build locally so that changes in the branch are used for linting.

Hypothetical: Some unreleased change that would determine whether the Stack linter passes needs to be merged, but the Stack linter will not pass without the unreleased change. Building locally would resolve this.

**Comment by nemchik** [comment]
Something like this might work
https://github.com/nemchik/super-linter/commit/746cfd8a7649dcd4897f369dfc563f1b3b158def
Possibly done alongside this PR so that it runs both ways.

**Comment by zkoppert** [comment]
Local staging branches workflow has been fixed at https://github.com/github/super-linter/pull/273/files. Please reopen if I have missed or misunderstood something.

**Comment by nemchik** [comment]
Please reopen.

Explanation:
https://github.com/github/super-linter/pull/273/files uses https://github.com/github/super-linter/blob/f1e46e8e76e65e3f96d06e780a9eebeeb701348e/.github/workflows/stack-linter.yml#L44 which pulls the latest release of the tool published to docker hub. This does not build the image locally and test using the image built. So you can lint the code prior to building the tool (which is good and necessary) but if you make a change to the code that would affect how the tool runs you would not be able to see validation that your changes work by pulling the latest release from docker hub.

The intention of this PR is to overcome the above challenge, and negate the need for contributors with permissions to merge on this repo to pull changes in for CI to run. CI will just run when a user opens a PR.

**Comment by nemchik** [comment]
Rebased (again) on top of current master.

**Pull request closed without merging**
