### PR TITLE
break out:

### PR DESCRIPTION
**Pull request by admiralAwkbar**
This Pr will cover:
- Fixing the folder structure
- Breaking down files better
- Making it easier to maintain

### CODE REVIEW

**Comment by ferrarimarco** [comment]
This is something I wanted to do! Great work.

**Comment by admiralAwkbar** [comment]
@ferrarimarco It has been bothering me for a while and needed to be done :)

**Comment by admiralAwkbar** [comment]
@ferrarimarco Its been done! Looks good and runs! can you give me some +1?

**Comment by admiralAwkbar** [comment]
@ferrarimarco Also sorry if this makes pulling in master to your other branch... could be fun...

**Review by jwiebalk — APPROVED** [review]

**Comment by ferrarimarco** [comment]
Nice work!

**Pull request merged**
