### PR TITLE
Add PHPStan support

### PR DESCRIPTION
**Pull request by WyriHaximus**
## Proposed Changes

1. Add PHPStan
2. Add support for detecting 

## Readiness Checklist

- [ ] Label as `breaking` if this is a large fundamental change
- [X] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

## Todo list

- [X] Add PHPStan
- [x] Add PHPStan more securely by checking the phars signature
- [x] Add support for detecting PHPStan configuration within the code being checked
- [x] Support to chose one (or more) particular linter(s) for specific language.

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Question for the reviewers, is there a way to use the `phpstan.neon` file from the repo root?

**Comment by filips123** [comment]
I think there is one additional thing to add to TODO list: Support to chose one (or more) particular linter(s) for specific language. Related issue is #472.

**Comment by WyriHaximus** [comment]
> I think there is one additional thing to add to TODO list: Support to chose one (or more) particular linter(s) for specific language. Related issue is #472.

@filips123 Added :+1:

**Comment by admiralAwkbar** [comment]
@WyriHaximus You could add the env var for the file location and have it point to the root of the repo. I think that would be a solid way of doing it

**Comment by WyriHaximus** [comment]
> > I think there is one additional thing to add to TODO list: Support to chose one (or more) particular linter(s) for specific language. Related issue is #472.
> 
> @filips123 Added

@filips123 Implemented, including test suite for it with TAP file with expected output.

**Comment by WyriHaximus** [comment]
> @WyriHaximus You could add the env var for the file location and have it point to the root of the repo. I think that would be a solid way of doing it

@admiralAwkbar Great idea, will add that tomorrow. Spent today fixing tests, and kicking the build a lot with force push because of networking failures 🤐

**Comment by WyriHaximus** [comment]
@admiralAwkbar ok added it, it will do a quick check if the file exists or not and falls back to the default template

**Comment by filips123** [comment]
This should also be implemented for my PHPCS and Psalm PR, right?

**Comment by WyriHaximus** [comment]
@filips123 I assume so yes, waiting for feedback from @admiralAwkbar on it. Especially since it diverges from the default for other linters

**Comment by admiralAwkbar** [comment]
@WyriHaximus Thank you for the amazing work on this and driving this to get done! again amazing work!

**Pull request merged**
