### PR TITLE
Update README.md Ansible-lint configuration file link

### PR DESCRIPTION
**Pull request by chrisedebo**
Updated Ansible-lint configuration file link. Old link is now a 404

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by SaintMara59** [comment]
І have 1 cool idea, and sho need Davy , don't take me slip; end wake me up! + 1 F-n;

**Comment by Hmzahali** [comment]
Hi

**Review by Hmzahali — APPROVED** [review]

**Comment by SaintMara59** [comment]
👋

**Comment by SaintMara59** [comment]
👍

**Comment by zkoppert** [comment]
👋🏻 @chrisedebo this repository is now being actively developed at https://github.com/super-linter/super-linter. You can make your pull request there and we will close this here. Thanks!

**Pull request closed without merging**
