### PR TITLE
Added support for jsx and tsx files

### PR DESCRIPTION
**Pull request by thematchless**
I added support for linting jsx and tsx files (Utilizing: eslint) https://github.com/github/super-linter/issues/352

## Changes
- added the recognition of .jsx and .tsx files
- added two config params to control the linting

### CODE REVIEW

**Comment by thematchless** [comment]
converting to draft because the test cases are missing

**Comment by admiralAwkbar** [comment]
@thematchless since it uses the same linting command, wouldn't it be more simple to just add those file extensions to the standard js loops? or do they really need to be treated as another language to manage? Just trying to understand better the path you took. Thanks! Also, my knowledge of those is super limited...

**Comment by thematchless** [comment]
@admiralAwkbar that was my first attempt to solve this. But i thought it would be nicer if you could control if you really want to lint the .jsx or .tsx files. There might be some guys who want their javascript checked but not their .jsx files.

**Comment by admiralAwkbar** [comment]
@thematchless makes sense.. and agree :)

**Pull request merged**
