### PR TITLE
Update black binary to 21.12b0

### PR DESCRIPTION
**Pull request by pdonorio**
Release reference:
https://github.com/psf/black/releases/tag/21.12b0

### CODE REVIEW

**Comment by ferrarimarco** [comment]
@pdonorio thanks for this PR.

@admiralAwkbar why aren't we installing black via pip? I remember some dependency conflicts? Maybe it's time to retry?

**Comment by jalaziz** [comment]
> @pdonorio thanks for this PR.
> 
> @admiralAwkbar why aren't we installing black via pip? I remember some dependency conflicts? Maybe it's time to retry?

@ferrarimarco This was changed because `snakefmt` has a dependency on `black` that prevented upgrading to 21.x releases. While the `snakefmt` dependency on `black` has been upgraded, we'll run into the same issues with 22.x releases and so forth.

The best solution at the time seemed to be to use the "binary" version of `black` to allow independent upgrades.

**Comment by pdonorio** [comment]
Hello, any reason why this is not being merged?

**Comment by admiralAwkbar** [comment]
@pdonorio As you can see from the information above by @ferrarimarco , This seems to break the current model and will need a better way to install or we have broken upgrades every time.

**Comment by jalaziz** [comment]
> @pdonorio As you can see from the information above by @ferrarimarco , This seems to break the current model and will need a better way to install or we have broken upgrades every time.

@ferrarimarco @admiralAwkbar To be honest, the current way of installing using one `requirements.txt` has been broken for a while. The interdependencies of the different formatters prevent independent upgrades.

I've been thinking about it more and the best solution might be independently managed virtual environments (through pipx or another tool). The challenge would then be having to have a separate `requirements.txt` for each tool if you want depdendabot to handle updates.

**Comment by admiralAwkbar** [comment]
@jalaziz I think that might be the best way to achieve this... With so many tools and deps, this has become a burden and that sounds like the right answer to getting this more modular, and supportable.
Just need to put in the work to get to that format

**Comment by admiralAwkbar** [comment]
This was solved in the python deps pr #2294

**Pull request closed without merging**
