### PR TITLE
Work on adding Java

### LINKED ISSUE #115: Java Support
Really appreciate the efforts that already went into `super-lint`, it would be great to also add support for Java using perhaps one of the following linters:

- https://github.com/checkstyle/checkstyle
- https://github.com/spotbugs/spotbugs
- https://github.com/pmd/pmd

### PR DESCRIPTION
**Pull request by quackduck**
# Proposed Changes
Work on adding Java

Fixes #115

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@quackduck cleaned up some of the first issues looks like your in good shape to keep going :)

**Comment by quackduck** [comment]
Thank you so much!
What are the other issues?

**Comment by quackduck** [comment]
Ah I see there's a lot of angle brackets left to fix.

**Comment by quackduck** [comment]
I hope there isn't any duplicate code. The way I found merge conflicts was by searching for angle brackets 😬 .

**Comment by admiralAwkbar** [comment]
@quackduck seems to be in good shape, adding the last pieces now :) then some testing

**Comment by admiralAwkbar** [comment]
@IAmHughes want to take a swing at fixing the example good code :)

```bash
2020-08-05 20:01:11 [INFO  ]   File:[/tmp/lint/.automation/test/java/java_good_1.java]
2020-08-05 20:01:12 [ERROR ]   Found errors in [checkstyle] linter!
2020-08-05 20:01:12 [ERROR ]   [Starting audit...
[ERROR] /tmp/lint/.automation/test/java/java_good_1.java:1: Missing package-info.java file. [JavadocPackage]
[ERROR] /tmp/lint/.automation/test/java/java_good_1.java:3:1: Utility classes should not have a public or default constructor. [HideUtilityClassConstructor]
[ERROR] /tmp/lint/.automation/test/java/java_good_1.java:3:7: Name 'java_good' must match pattern '^[A-Z][a-zA-Z0-9]*$'. [TypeName]
[ERROR] /tmp/lint/.automation/test/java/java_good_1.java:4:1: '{' at column 1 should be on the previous line. [LeftCurly]
[ERROR] /tmp/lint/.automation/test/java/java_good_1.java:7:29: Parameter args should be final. [FinalParameters]
[ERROR] /tmp/lint/.automation/test/java/java_good_1.java:7:40: Array brackets at illegal position. [ArrayTypeStyle]
[ERROR] /tmp/lint/.automation/test/java/java_good_1.java:8:5: '{' at column 5 should be on the previous line. [LeftCurly]
Audit done.
```

**Comment by IAmHughes** [comment]
@quackduck thanks for starting this PR. I fixed the test file finally 🤦‍♂️. @admiralAwkbar et all, this should be ready to go now.

**Comment by quackduck** [comment]
We're getting npm errors somehow 😮 
Sacrificed consistency for compilability. (I changed the name of the good java file)
By the way, the bad java file is missing an ending quote and a semicolon [here](https://github.com/github/super-linter/pull/459/commits/ef62a7081c7b10dfee20b640e4e5489593e46778#diff-895105a9a87eaff9f550c1493da1cee5L9-R7):
```java
System.out.println("Hello, World)
```
I don't think that's a good test for checkstyle because even the compiler would catch those. I'll find some better tests.

**Comment by quackduck** [comment]
Are you trying to make it compilable?
If so, that still wouldn't compile because it's missing a semicolon.

**Comment by admiralAwkbar** [comment]
@quackduck good catch! sorry, java is not my strongest :)

**Comment by quackduck** [comment]
That's alright!
Also, does checkstyle still throw lint errors on it?

**Comment by IAmHughes** [comment]
> Also, does checkstyle still throw lint errors on it?

jfyi, the linter runs in this job: `.github/workflows/deploy-DEV.yml / Deploy Docker Image - DEV (pull_request) ` shown in the checks at the bottom of your PR:

image

✔️ means we're good to go. Agree the bad file should still compile, just have poor standard practices such as `{` on next line, extra spaces, etc.

@admiralAwkbar @jwiebalk if you wanna give it a once over, I think we're good to merge as of now.

**Comment by quackduck** [comment]
I wish it showed the error message the linter throws :)

**Comment by IAmHughes** [comment]
> I wish it showed the error message the linter throws :)

What error message? The linter didn't have errors, hence the passing test case. You can click `Details` and see the step called `Run test cases` which would show the details of what linter(s) found errors and what the errors were. Since it passed, there were no errors in the `_good` files which is expected, and any `_bad` file is supposed to have an error so we don't raise those as errors in the linter output.

**Comment by quackduck** [comment]
Yeah, I agree it shouldn't exit with a non-zero exit code.
What I meant was when the bad test cases are run, super-linter should show the errors generated by the individual, sub-linters (like checkstyle). Of course, this isn't needed, it's just that I was curious 🙂

**Comment by IAmHughes** [comment]
> What I meant was when the bad test cases are run, super-linter should show the errors generated by the individual, sub-linters (like checkstyle)

@quackduck - I see what you're saying, but the way test cases work are a little different (and is pretty standard imo). It is expected that the file should fail because we're just testing that the linter correctly has some linting error found. We don't output all the `_bad` files because again, the assertion is that the linter SHOULD find an error, not caring what the error is. Likewise `_good` is ensuring the linter doesn't find any errors.

**Comment by quackduck** [comment]
> > What I meant was when the bad test cases are run, super-linter should show the errors generated by the individual, sub-linters (like checkstyle)
> 
> 
> 
> @quackduck - I see what you're saying, but the way test cases work are a little different (and is pretty standard imo). It is expected that the file should fail because we're just testing that the linter correctly has some linting error found. We don't output all the `_bad` files because again, the assertion is that the linter SHOULD find an error, not caring what the error is. Likewise `_good` is ensuring the linter doesn't find any errors.

Yes, I agree, it _should_ find errors. I was just curious as to what those errors were.

**Pull request merged**
