### PR TITLE
Adding deploy For releases

### PR DESCRIPTION
**Pull request by admiralAwkbar**
- Adding GitHub Actions for Release deployment

### CODE REVIEW

**Comment by zkoppert** [comment]
Can we update the Contributing.md to point to this in the release section?

**Comment by zkoppert** [comment]
How will version numbers be incremented?

**Comment by admiralAwkbar** [comment]
@zkoppert We need to update the docs on this now... :)
But we should have a workflow now that deploys the Docker images when we create a release

**Comment by admiralAwkbar** [comment]
@zkoppert I'm using the semantic versioning in the following:
- X.Y.Z
  - X major change to the linter and how it works
  - Y adding new features or functionality
  - Z bug fixes

**Pull request merged**
