### PR TITLE
State linter

### PR DESCRIPTION
**Pull request by admiralAwkbar**
This PR will add:
- AWS States Language linting
- Fixed up some code
- Cleaned it up real good...

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@jwiebalk and I paired on this to get it going...
@Link- this should help with that cool stuff you were showing off :)

**Comment by admiralAwkbar** [comment]
@nemchik any chance you can hook up the braces in this? seems the merge conflicts caused some fun and had to dump a few of your changes

**Comment by admiralAwkbar** [comment]
@v1v any idea what's going on with the tap format check?
Seems t blow up on coffee...

**Comment by v1v** [comment]
I've just verified locally with the master branch and no issue, but if I checkout this PR then I'm able to reproduce the error:

```
---------------------------
File:[/tmp/lint/.automation/test/coffeescript/coffeescript_good_1.coffee]
ERROR! Found errors in [coffeelint] linter!
ERROR:[internal/fs/utils.js:230
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:564:3)
    at tryReadSync (fs.js:349:20)
    at Object.readFileSync (fs.js:386:19)
    at read (/node_modules/@coffeelint/cli/lib/commandline.js:62:15)
    at readConfigFile (/node_modules/@coffeelint/cli/lib/commandline.js:128:12)
    at loadConfig (/node_modules/@coffeelint/cli/lib/commandline.js:140:18)
    at Object.<anonymous> (/node_modules/@coffeelint/cli/lib/commandline.js:248:14)
    at Object.<anonymous> (/node_modules/@coffeelint/cli/lib/commandline.js:279:4)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/node_modules/@coffeelint/cli/bin/coffeelint:34:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
 {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}]
ERROR: Linter CMD:[coffeelint -f / /tmp/lint/.automation/test/coffeescript/coffeescript_good_1.coffee]
```

As far as I see the issue is with the coffee linting for the .automation/test/coffeescript/coffeescript_good_1.coffee file:
 `Linter CMD:[coffeelint -f / /tmp/lint/.automation/test/coffeescript/coffeescript_good_1.coffee]` therefore the expected TAP validation fails as expected.

I wonder if the issue could be related to the changes in `dependencies/package-lock.json`?

**Comment by Link-** [comment]
@admiralAwkbar Ohhh yeah!! <3

**Comment by admiralAwkbar** [comment]
@nemchik thank you for the help! we got it!

**Pull request merged**
