### PR TITLE
Add rustfmt for Rust

### PR DESCRIPTION
**Pull request by yanganto**
- add 2015 edition
- add 2018 edition

## Proposed Changes
1. Support Rust with rustfmt

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by yanganto** [comment]
@admiralAwkbar Please review this.

There is only one linter error as following and not caused by this PR.

Here is the linter error.
```
2021-02-25 16:24:34 [ERROR]   Found errors in [hadolint] linter!
2021-02-25 16:24:34 [ERROR]   Error code: 1. Command output:
------
Dockerfile:138 DL3044 error: Do not refer to an environment variable within the same `ENV` statement where it is defined.
------
2021-02-25 16:24:34 [DEBUG]   Error code: 1. Command output:
------
Dockerfile:138 DL3044 error: Do not refer to an environment variable within the same `ENV` statement where it is defined.
```
And it is caused by adding node tools into PATH as following
```
ENV PATH="/node_modules/.bin:${PATH}"
```

**Comment by admiralAwkbar** [comment]
@yanganto fixed it :)

**Comment by yanganto** [comment]
@admiralAwkbar Thanks for the review.  

It will be super nice if super-linter including Rust. 

If there are issues with Rust in the future, please kindly pin me.  I know there is an issue about `clippy` now,  and it depends on the other [issue](https://github.com/rust-lang/rust-clippy/issues/2001), and `clippy` is not a tool for can in one file by one file way, such that I use `rustfmt` at this moment.

Thanks.
:)

**Comment by yanganto** [comment]
Thanks for review

**Pull request merged**
