### PR TITLE
Updates terrascan to v1.3.1

### PR DESCRIPTION
**Pull request by cesar-rodriguez**
This updates Terrascan to the tagged docker image for v1.3.1. 

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@cesar-rodriguez The issue is that the updated linter puts time stamps in the report, and that is breaking our tap check...

Need to find a better way to solve this

**Comment by admiralAwkbar** [comment]
@GaboFDC @ferrarimarco  it seems we cant stop the time stamps, so I'm turning tap. validate off for now... this should get us moving forward and we can see about that in the future

**Comment by ferrarimarco** [comment]
@admiralAwkbar one thing I did in similar cases is to tweak the function in tapLibrary.sh

**Comment by ferrarimarco** [comment]
This one: https://github.com/github/super-linter/blob/master/lib/functions/tapLibrary.sh#L21

There are various cases there where I hide the milliseconds duration for example, and other dynamic parts of other tests

**Comment by admiralAwkbar** [comment]
@ferrarimarco Awseome
i think i will move this along and open a new issue to fix tap on it.
Always moving forward...

**Comment by ferrarimarco** [comment]
Do we still support ignored taps? I didn't know :)

**Comment by admiralAwkbar** [comment]
Opened #1166

**Comment by ferrarimarco** [comment]
It's a matter of piping another `sed` invocation with the right regex :)

**Comment by ferrarimarco** [comment]
That's what I meant LOL

`2021-01-27 19:40:02 [FATAL]   No TAP expected file found at:[/tmp/lint/.automation/test/terraform_terrascan/reports/expected-TERRAFORM_TERRASCAN.tap]`

**Comment by admiralAwkbar** [comment]
@ferrarimarco lol i forgot we made it not avilable... any help you can give on the tap? i feel like I never got it..

**Comment by ferrarimarco** [comment]
I'm not near my workstation now, but the process is:

1. Have a look at the produced TAP output and compare it with the expected
2. Get what you need to do to make the two identical. Example: remove all the timestamps.
3. Copy the
4. Open your favorite shell.
4. Pipe the content of the produced report to the various `awk`, `sed` and `tr` invocations that you find in https://github.com/github/super-linter/blob/master/lib/functions/tapLibrary.sh#L30 (even by copying and pasting the commands in your shell).
5. Add a new `sed` with a regex that removes the timestamp. https://www.debuggex.com/ helped me a number of times.

This should be relatively straightforward. If you still have issues, can you post both TAPs (expected and produced) so that I can give it a shot.

**Review by monstro805 — APPROVED** [review]

**Review by monstro805 — DISMISSED** [review]

**Comment by ausfestivus** [comment]
Is there a way to bump this and reopen the PR? The terrascan thats included in the current super-linter release makes the super-linter less useful.

**Comment by admiralAwkbar** [comment]
@ausfestivus Were working on fixing the tests now, so we can start bumping the versions again.
Seems this was one of the bumps that ultimately broke the tap format testing.

Hope to have this worked out this week

**Comment by elreydetoda** [comment]
@admiralAwkbar , will you end up posting back here when it is fixed? Also, is there anything we ( anyone that wants to ) can do to help?

**Comment by cesar-rodriguez** [comment]
@elreydetoda Seems like this was fixed and Terrascan was updated to v1.4.0 on #1422

**Comment by elreydetoda** [comment]
Awesome, thanks @cesar-rodriguez  for the info :grin: 
I was pinned a version back :sweat_smile:

**Pull request closed without merging**
