### PR TITLE
Uninstall Dockerfilelint

### LINKED ISSUE #2179: Remove Dockerfilelint
While working on #2178, I've noticed that [Dockerfilelint](https://github.com/replicatedhq/dockerfilelint) didn't see any development in more than one year.

Can we remove that from super-linter, given that we already include [hadolint](https://github.com/hadolint/hadolint), which covers all the checks dockerfilelint covers,  plus more?

This would help make super-linter lighter, and simplify maintainability.

If we do this, we should also take care of properly migrating users away from dockerfilelint, if they explicitly enabled that linter, or configured it somehow.

/cc @admiralAwkbar @zkoppert

### PR DESCRIPTION
**Pull request by ferrarimarco**
Fixes #2179 

## Proposed Changes

Uninstall Dockerfilelint.

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [x] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

## Requisites

- [x] #2199
- [ ] #2215

### CODE REVIEW

**Comment by ferrarimarco** [comment]
@admiralAwkbar can you kindly update package.json and package-lock.json? I don't have the proper tooling handy on my dev workstation. Thanks!

**Comment by zkoppert** [comment]
Do you think this should be labelled as a breaking change? I could understand going either way.

**Comment by ferrarimarco** [comment]
@zkoppert done

**Comment by admiralAwkbar** [comment]
@ferrarimarco ask and you shall receive :)

**Comment by ferrarimarco** [comment]
thanks!

**Comment by ferrarimarco** [comment]
The PR is ready for review then :)

**Comment by admiralAwkbar** [comment]
@ferrarimarco lol somehow removing that broke r....

**Comment by ferrarimarco** [comment]
I checked, and I think this PR is not the root cause of that. Actually, I think the current main is affected by this issue as well.

**Comment by ferrarimarco** [comment]
The root cause is likely that the [icu-libs package](https://pkgs.alpinelinux.org/package/edge/main/x86_64/icu-libs) (upon which the [R package]() depends, doesn't include the [libicui18n.so.67 file](https://pkgs.alpinelinux.org/contents?file=libicui18n.so.67*&path=&name=&branch=edge)

**Comment by waja** [comment]
This change breaks existing setups where `.github/linters/.dockerfilelintrc` exists:

```
2021-12-21 05:34:08 [INFO]   ----------------------------------------------
2021-12-21 05:34:08 [INFO]   ----------------------------------------------
2021-12-21 05:34:08 [INFO]   Linting [DOCKERFILE_HADOLINT] files...
2021-12-21 05:34:08 [INFO]   ----------------------------------------------
2021-12-21 05:34:08 [INFO]   ----------------------------------------------
2021-12-21 05:34:08 [INFO]   ---------------------------
2021-12-21 05:34:08 [INFO]   File:[/github/workspace/.github/linters/.dockerfilelintrc]
2021-12-21 05:34:08 [ERROR]   Found errors in [hadolint] linter!
2021-12-21 05:34:08 [ERROR]   Error code: 1. Command output:
------
/github/workspace/.github/linters/.dockerfilelintrc:1:1 unexpected 'r' expecting '#', ADD, ARG, CMD, COPY, ENTRYPOINT, ENV, EXPOSE, FROM, HEALTHCHECK, LABEL, MAINTAINER, ONBUILD, RUN, SHELL, STOPSIGNAL, USER, VOLUME, WORKDIR, a pragma, end of input, or whitespaces 
------
```

**Pull request merged**
