### PR TITLE
Add clippy for rust

### LINKED ISSUE #108: Rust support
Using https://github.com/rust-lang/rust-clippy

### PR DESCRIPTION
**Pull request by yanganto**
Fixes #108 

## Proposed Changes
1. add wrapper script for `clippy` to lint project base on the manifest file, `Cargo.toml`

### Author/Contributor
- [X] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@yanganto 

Seems the error is:
```
/tmp/lint/.automation/test/rust_clippy/good /tmp/lint/.automation/test
    Checking good v0.1.0 (/tmp/lint/.automation/test/rust_clippy/good)
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `good`.
```

**Comment by djhelps1109** [comment]
add

**Comment by yanganto** [comment]
Hi @admiralAwkbar,
This PR is ready, and there is an issue complaint by `pipenv`, which this PR never touch the files relating to python linters.  Please kindly help with this.  Many thanks.
```
[pipenv.exceptions.InstallError]: Collecting cryptography==3.4.6
[pipenv.exceptions.InstallError]:   Using cached cryptography-3.4.6.tar.gz (546 kB)
[pipenv.exceptions.InstallError]: ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of setuptools.build_meta in pyproject.toml
ERROR: Couldn't install package: cryptography
```

**Comment by djhelps1109** [comment]
😋

**Review by admiralAwkbar — APPROVED** [review]

**Pull request merged**
