### PR TITLE
Update all NPM deps and Fix `ts-standard`

### PR DESCRIPTION
**Pull request by lindluni**
This change updates all NPM deps. This picks up several major changes including major changes to the `ts-standard` package.

In order to support the rewrite of the `ts-standard` linter, the `.automation` directory has been renamed to `automation` as `ts-standard` does not support searching hidden directories and does not respect the `eslint` `--ignore-pattern` negations when using the `eslint` plugin.

We still need to wait on one more release of the `ts-standard` NPM package, but my changes have landed upstream: https://github.com/standard/ts-standard/issues/276

### CODE REVIEW

**Comment by lindluni** [comment]
Need to add an EXCLUDE regex variable for our workflows now that the automation directory isn’t hidden

**Comment by lindluni** [comment]
Once this is merged we can update ts-standard to 12.0.2 and proceed to get everything back on track: https://github.com/standard/ts-standard/pull/277

**Comment by ferrarimarco** [comment]
Great to hear!

**Comment by lindluni** [comment]
Closing in favor of #3645 which doesn't require rewriting the `.automation` directory!

**Pull request closed without merging**
