### PR TITLE
Fix case of "Markdown"/"markdownlint", update link to rule documentation, add link to inline comment syntax.

### PR DESCRIPTION
**Pull request by DavidAnson**

### CODE REVIEW

**Comment by DavidAnson** [comment]
Cool, fixing the merge conflict now...

**Comment by admiralAwkbar** [comment]
As a text-only fix, no need to formally pull in branch for testing

**Comment by DavidAnson** [comment]
Oh, cool, thanks, just pushed the merge resolution anyway. :)

**Comment by DavidAnson** [comment]
@admiralAwkbar you can see the diff after the merge here: https://github.com/DavidAnson/super-linter/commit/a652839203be346638f913350bbcea1a594ea735

I can send a new PR if you'd like?

**Comment by admiralAwkbar** [comment]
@DavidAnson thank you, please. missed it in the merge conflicts, my bad...

**Pull request merged**
