### PR TITLE
Fix bad owner/group flags on node dependencies

### LINKED ISSUE #3901: issue with pulling ghcr.io/github/super-linter:slim-v4.10.1
## Describe the bug

We started experiencing issues with super linter, after upgrade to v4.10.0. Most recent example is that we are running into the issue with pulling ghcr.io/github/super-linter:slim-v4.10.1

Pull fails with an error:

failed to register layer: ApplyLayer exit status 1 stdout:  stderr: failed to Lchown "/node_modules/ast-types-flow/README.md" for UID 369884941, GID 1876110778 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /node_modules/ast-types-flow/README.md: invalid argument
  Warning: Docker pull failed with exit code 1, back off 7.258 seconds before retry.
  /home/ubuntu/bin/docker pull ghcr.io/github/super-linter:slim-v4.10.1

## Expected behavior

Pull should work

## Steps to Reproduce
Run rootless docker inside docker and try to pull image ghcr.io/github/super-linter:slim-v4.10.1

It sounds like one of the NPM dependencies has exotic uid/guid ownership and rootless docker is failing to pull that depedency. Can you please fix it.

### PR DESCRIPTION
**Pull request by ajkerr**
Fixes #3901

## Proposed Changes

Based on the suggestion in https://github.com/github/super-linter/issues/3901#issuecomment-1464867637, this PR introduces a step in the `Dockerfile` to clean up the bad uid/gid in `node_modules`. The bad dependency is the unmaintained `ast-types-flow`, but doing the entire `node_modules` directory seems fine.

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
@ajkerr this probably should be added in the same RUN instruction than npm install, to avoid any docker image layer to contain files with out of reach uid :)

**Comment by ajkerr** [comment]
> his probably should be added in the same RUN instruction than npm install, to avoid any docker image layer to contain files with out of reach uid :)

Good call, will change.

**Comment by ajkerr** [comment]
Any chance this could make it into the next release?

**Review by lindluni — APPROVED** [review]

**Comment by echoix** [comment]
After working on the ast-types-flow project, a new version was released this weekend (repackaged from a clean Docker environnement, no real changes), and apparently the problem isn't there anymore. I'm curious to see if there are other node modules that cause this now. 

> Getting the package with `npm pack ast-types-flow@0.0.8` and then checking the contents of the package with `tar -ztvf ast-types-flow-0.0.8.tgz` leads to this:

> ```
-rw-r--r--  0 0      0        1067 Oct 26  1985 package/LICENSE
-rw-r--r--  0 0      0      122152 Oct 26  1985 package/lib/types.js
-rw-r--r--  0 0      0         749 Oct 26  1985 package/package.json
-rw-r--r--  0 0      0        2007 Oct 26  1985 package/README.md
```

> Looks good! Thanks @kyldvs!

> _Originally posted by @rmehner in https://github.com/kyldvs/ast-types-flow/issues/5#issuecomment-1509619333_

**Comment by rmehner** [comment]
> After working on the ast-types-flow project, a new version was released this weekend (repackaged from a clean Docker environnement, no real changes), and apparently the problem isn't there anymore. I'm curious to see if there are other node modules that cause this now.

@echoix 

I got the error message "ApplyLayer exit status 1 stdout:  stderr: Container ID 369884941 cannot be mapped to a host ID" and then did this in the docker container to find the offending module:

`find / \( -uid 369884941 \)  -ls 2>/dev/null`

This is a bit more tricky when it's an intermediate layer, but if you do have access to the Dockerfile, it's possible to reproduce with a bit of work.

**Comment by echoix** [comment]
I know the bug, I'm the one who worked on the workaround in megalinter

**Comment by rmehner** [comment]
@echoix just tried to be helpful, because you wrote: 

>  I'm curious to see if there are other node modules that cause this now.

and I wanted to show my way of finding out which node_module was the culprit in case you didn't know how to do this :)

**Comment by echoix** [comment]
Oh, sorry! It's in the superlinter 5 image that you find others? Usually the problem is with ids with high numbers, that go out of a restricted range of ids for a restricted Docker setup, not only that specific one.

**Pull request merged**
