### PR TITLE
De-duplicate workflows

### LINKED ISSUE #2205: Triggering workflows on pull requests
Triggering deploy-DEV workflows on PRs coming from forks seems like a thing we should do, otherwise we're going to miss a big chunk of checks.

Thoughts?

References

- https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

### PR DESCRIPTION
**Pull request by ferrarimarco**
## Proposed Changes

1. De-duplicate workflows using a matrix.

Fixes #2205

### TODO

- [ ] Ensure the test suite and the inspec check run in every case. (See #2255 for details about why it's needed).

(requires #2178)

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [x] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by ferrarimarco** [comment]
@admiralAwkbar if you like the concept behind this PR, I can go ahead and de-duplicate the other workflows as well.

**Comment by admiralAwkbar** [comment]
@ferrarimarco I love this PR!
please any other help is much appreciated

**Comment by ferrarimarco** [comment]
Hi @admiralAwkbar

I'll have a look at this in the coming days :)

**Comment by admiralAwkbar** [comment]
@ferrarimarco Hey! thanks! I took a quick stab at reducing as well. THis is a fun PR

**Comment by admiralAwkbar** [comment]
@ferrarimarco I think its right but would love a code check :)

**Comment by ferrarimarco** [comment]
ah! yep, let me check. Thanks for pushing this, I've been swamped

**Comment by ferrarimarco** [comment]
LGTM. I can't add a review for my own PR, but you can @admiralAwkbar 

Thanks for pushing this over the last mile!

**Pull request merged**
