### PR TITLE
Update snakefmt to 0.3.0 and black to 20.3 (now supported by snakefmt).

### PR DESCRIPTION
**Pull request by jlewis91**
## Proposed Changes

1. Update snakefmt (0.2 -> 0.3) and black (19-> 20) versions
2. snakefmt 0.3 now supports black 20.3, so the version pinning issues with black should now be resolved
3. This is a 'breaking' change as black 20 has formatting differences vis a vis black 19
4. As part of version updating, ansible 5.0 came along for the ride, this required a new regex to filter out a build duration printout which cannot be handled in a TAP file
5. And due to piplock dependency updates, the following PRs can be closed / are irrelevant: #1207 #1200 #1195 #1191

### Reviewing Maintainer
- [x] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by jlewis91** [comment]
Resolves https://github.com/github/super-linter/issues/807 more permanently

**Comment by jlewis91** [comment]
Resolves:
* https://github.com/github/super-linter/pull/1207
* https://github.com/github/super-linter/pull/1200

**Comment by jlewis91** [comment]
@admiralAwkbar Looking forward to a review, let me know if changes are necessary! :)

**Comment by ferrarimarco** [comment]
Assigning to @admiralAwkbar because it's a relatively big change.

**Comment by ferrarimarco** [comment]
Thanks @jlewis91 for this PR and for fixing other tests as well!

**Review by GaboFDC — APPROVED** [review]
Nice work, really apprretiated, would wait for @admiralAwkbar to give the final go, but seems good.

**Review by admiralAwkbar — APPROVED** [review]
Amazing work!

**Pull request merged**
