### PR TITLE
Update black binary to 21.9b0

### PR DESCRIPTION
**Pull request by jalaziz**
[Release Notes](https://github.com/psf/black/releases/tag/21.9b0)

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by jalaziz** [comment]
This is currently broken as it seems like the latest black binary is throwing a new error.

**Comment by admiralAwkbar** [comment]
@jalaziz  Looks like this resolved itself and since we have redeployed were up to date?

**Comment by jalaziz** [comment]
> @jalaziz Looks like this resolved itself and since we have redeployed were up to date?

The issue was resolved, but `black` hasn't published new binaries as far as I can tell. I'm watching out for that to update this PR once it's been deployed.

That being said, it looks like `snakefmt` recently merged in the change that would allow `black` to be updated through `pip`. That being said, the binary version of `black` is probably still useful long term.

I don't believe super-linter is up-to-date though as the binary is still pointing to 21.7b0, unless i missed something? The 21.8b0 binary is certainly broken and it doesn't seem like black has republished it yet, so we might have to wait until the next release.

**Comment by jalaziz** [comment]
@admiralAwkbar This PR should be good now.

**Review by admiralAwkbar — APPROVED** [review]

**Comment by admiralAwkbar** [comment]
@jalaziz Thanks for keeping up with this one!

**Pull request merged**
