### PR TITLE
Add env `BASH_SEVERITY` to specify severity of errors in `shellcheck` for bash validation

### PR DESCRIPTION
**Pull request by bowenliang123**
## Proposed Changes
Currently bash validation is executed with `severity` in the default value of `style`, which makes too many `info` level messages thrown and causes failures in using `super-linter`. For the users only cares about severity of  warning and above, there's no way to config it in `super-linter`.

1. support specifying minimum severity in `shellcheck` for bash validation by adding BASH_SEVERITY env
2. make use of option `--severity` in `shellcheck` (https://github.com/koalaman/shellcheck/blob/master/shellcheck.1.md#options)

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by bowenliang123** [comment]
cc @admiralAwkbar @ferrarimarco

**Comment by bowenliang123** [comment]
Anybody help me to push this feature forward ? Like approval for CI jobs, and help me to pass the test. Thanks.

**Comment by bowenliang123** [comment]
My changes don't affect to `ansible-lint`, but the execption encounters.

Anyone could help?

https://github.com/github/super-linter/actions/runs/4416946109/jobs/7764105838?pr=3984#step:7:243
```
  ×  super-linter-installed-commands: Super-Linter installed commands check (1 failed)
     ✔  Command: `command -v actionlint` exit_status is expected to eq 0
     ✔  Command: `actionlint --version` exit_status is expected to eq 0
     ✔  Command: `actionlint --version` stdout is expected to match /(.*?)/
     ✔  Command: `command -v ansible-lint` exit_status is expected to eq 0
     ✔  Command: `ansible-lint --version` exit_status is expected to eq 0
     ×  Command: `ansible-lint --version` stdout is expected to match /(.*?)/
     incompatible encoding regexp match (Windows-31J regexp with ASCII-8BIT string)
```

**Comment by lindluni** [comment]
The ansible issues should be fixed now, apologies for how long this took, had to dig into those failures on `main` as well as a deprecated NPM package.

**Comment by ferrarimarco** [comment]
Why introduce this environment variables? Can't you set the severity in a [`.shellcheckrc` file](https://github.com/koalaman/shellcheck/blob/master/shellcheck.1.md#rc-files)?

**Comment by ferrarimarco** [comment]
Why introduce this environment variables? Can't you set the severity in a [`.shellcheckrc` file](https://github.com/koalaman/shellcheck/blob/master/shellcheck.1.md#rc-files)?

**Comment by bowenliang123** [comment]
> Why introduce this environment variables? Can't you set the severity in a [`.shellcheckrc` file](https://github.com/koalaman/shellcheck/blob/master/shellcheck.1.md#rc-files)?

Negative.
`.shellcheckrc` rule file does not support `severity` directives, according to shellcheck's source code and wiki (https://www.shellcheck.net/wiki/Directive). The only way to set `severity`  is command line option `--severity=` , referring to your link (https://github.com/koalaman/shellcheck/blob/master/shellcheck.1.md#rc-files)

**Comment by bowenliang123** [comment]
> The ansible issues should be fixed now, apologies for how long this took, had to dig into those failures on `main` as well as a deprecated NPM package.

Thanks for the ping. And I have rebased my changes on the latest commit of the master branch. Let's see whether it passes the CI builds.

**Comment by bowenliang123** [comment]
Would you like to rerun CI builds and have some reviews or guidance on this PR, as it is submitted over one month ago ? @lindluni

**Comment by bowenliang123** [comment]
Thanks for the merge and help from @lindluni and @ferrarimarco. Is this feature available in the github action only when it's released in the next tag?

**Comment by lindluni** [comment]
Hi @bowenliang123 

It will be available on the “latest” tag once this workflow completes: https://github.com/github/super-linter/actions/runs/4717260552

**Comment by lindluni** [comment]
I will get a 5.0.1 published later this week for pinning purposes so the Action can be used directly

**Comment by bowenliang123** [comment]
No problem. I will try to apply this feature in Apache Kyuubi for bash shell check when it's available in action.

**Comment by bowenliang123** [comment]
> Hi @bowenliang123
> 
> It will be available on the “latest” tag once this workflow completes: https://github.com/github/super-linter/actions/runs/4717260552

Hi, kind ping to @lindluni . It seems the `latest` tag still refer to v4 (v4.10.0) but not v5, when using `github/super-linter/slim@latest` in https://github.com/apache/kyuubi/pull/4748 .  see log: https://github.com/apache/kyuubi/actions/runs/4761101004/jobs/8462033635?pr=4748#step:2:1

Therefor, this feature is unavailable with the `latest` tag.

**Pull request merged**
