### PR TITLE
only error on rstats lintr errors, not all lints

### LINKED ISSUE #1232: rstats lintr errors on all lints
## Describe the bug

the lintr linter for rstats errors on *all* lints...

## Expected behavior

... should error only on errors.

## Source

I'm skipping the reprex, because the code is pretty straightforward about the behavior:

https://github.com/github/super-linter/blob/b6bbc88e8e3ce21da52df376e0c3c080cb331c59/lib/functions/worker.sh#L221

`lintr::lint()` will always return all lints, not just errors, so this behavior might be a bit trigger happy.

I'm assuming that the general assumption for linters in super-linter is that they carry forward the error/warning/info etc. designations of the upstream linters.

### PR DESCRIPTION
**Pull request by maxheld83**
Fixes #1232.

paging @assignUser who added lintr support in the first place 🙏  in #569.

lintr does not have a native capability to filter by type, barring https://github.com/jimhester/lintr/issues/309, so we need some purrs action, which happily is included in the image.

## Proposed Changes

1. what it says on the tin; only errors on errors.

### Author/Contributor

No docs changes necessary.

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@maxheld83 i like it
trying to get tap to pass... its been a mess lately

**Comment by maxheld83** [comment]
the failing check is unrelated to my PR though, right?

**Comment by admiralAwkbar** [comment]
@maxheld83 
the tap is failing with message:
```
message: Warning message \nIn options(stringsAsFactors = TRUE)  \n  'options(stringsAsFactors = TRUE)' is deprecated and will be disabled\nError in loadNamespace(name)   there is no package called purrr\nCalls     ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart\nExecution halted\n
```

**Comment by admiralAwkbar** [comment]
@maxheld83 @assignUser 
It seems we pull in R from
`FROM ghcr.io/assignuser/lintr-lib:0.1.2 as lintr-lib`

Would we need to do a separate install of purr or pull from a diff image??

**Comment by assignUser** [comment]
> Would we need to do a separate install of purr or pull from a diff image??

I will update the image with purrr when I have a moment.

**Comment by maxheld83** [comment]
sorry, my bad. 

I was sloppy and had yesterday only tested:

`docker run ghcr.io/assignuser/lintr-lib:latest Rscript -e "purrr::map(c(1), sum)"` which worked alright.

So it seems that purrr was *already* in `latest` as of yesterday, @assignUser.

**Comment by assignUser** [comment]
@maxheld83 up until now `latest`and `v0.1.2` where identical (at least I thought so^^). I updated the image to include purrr in v0.2.0. 
Update your pr to: `FROM ghcr.io/assignuser/lintr-lib:0.2.0 as lintr-lib` that should do it.

**Comment by maxheld83** [comment]
argh, shoot, still have to update the TAP snapshots I guess ...

**Comment by maxheld83** [comment]
yikes, finally all passing.

Here's what I was missing:

- the TAP snapshot had an unrelated diff, caused by the change of the R version, I think? (something something `stringsAsFactors`)
- previously, the lintr would error out on *every lint*, not just errors (changing that is the point of this PR).
     Now with the more generous behavior, the test failed because the `bad.R` actually had caused no *errors*, just lints.
     So now there's an error in there and the snapshot has also been changed.

**Review by admiralAwkbar — APPROVED** [review]

**Pull request merged**
