### PR TITLE
Powershell support

### PR DESCRIPTION
**Pull request by admiralAwkbar**
Adds Powershell support via PSScriptAnalyzer

1. Adds Powershell into the DockerFile image
1. Creates a pwshlint.ps1 file to make PSScriptAnalyzer behave more "bash friendly" for how this program works
1. Supports exit codes
1. Has regex for powershell file extensions
1. Test-Automation test cases added for good ps1, bad ps1, psm1, and psd1

### CODE REVIEW

**Comment by admiralAwkbar** [comment]
@JustinGrote what are the files:
- `.automation/test/powershell/powershell.psd1`
- `.automation/test/powershell/powershell.psm1`

Just want to make sure I fully understand the logic

**Comment by JustinGrote** [comment]
@admiralAwkbar this is a powershell module and manifest, respectively. They are both valid powershell and wanted to make sure my matcher regex picked them up too.

**Comment by admiralAwkbar** [comment]
@JustinGrote is it ok if in name the like the other tests?
i.e. powershell_good_x.ps1` etc..

**Comment by JustinGrote** [comment]
> @JustinGrote is it ok if in name the like the other tests?
> i.e. `powershell_good_x.ps1` etc..
> 

Go for it, I'm not investing any more in this PR as I've rewritten super-linter in PowerShell :)

https://github.com/justingrote/super-duper-linter

**Comment by admiralAwkbar** [comment]
@michaelsainz Any chance you can look over the PowerShell fun?

**Comment by admiralAwkbar** [comment]
Seems Ruby is doing something odd again... looking into test container

**Comment by admiralAwkbar** [comment]
@zkoppert I think we have it now :)

**Comment by michaelsainz** [comment]
Sorry I missed this - was OOO for a couple days. But this PowerShell code that @JustinGrote wrote is ✨.

**Pull request merged**
