### PR TITLE
Add colors to output

### PR DESCRIPTION
**Pull request by nemchik**

### CODE REVIEW

**Comment by IAmHughes** [comment]
Thanks for starting on this, I have a local branch but I didn't get too deep into it yet, this looks promising so far 👍

**Comment by nemchik** [comment]
No problem. I've got some more commits to make in this branch but the CI is already looking promising.

**Comment by nemchik** [comment]
So far so good:

image

**Comment by admiralAwkbar** [comment]
so dank...

**Comment by nemchik** [comment]
https://github.com/nemchik/super-linter/actions/runs/154570227
https://github.com/nemchik/super-linter/actions/runs/154569460
Just for fun so we can see how it looks.

**Comment by nemchik** [comment]
Well one of my tests that was intended to break things did not because it wasn't code from inside the folder where the tests were being performed :smile: but the other failed as expected and you can see how it looks https://github.com/nemchik/super-linter/runs/828227902

It's god-awful! Makes me want to not make mistakes in my code and have to see how ugly it is!

**Comment by nemchik** [comment]
Also this is ready now.

**Pull request merged**
